---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-truenas-iscsi-retain # use csi-truenas-iscsi-retain if redeploy
  resources:
    requests:
      storage: 1Gi
