---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      version: 10.5.2
      chart: bazarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v1.0.4
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: "subtitles"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "{{ .Release.Name }}-tls"
            hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
    nfs-nas-tv:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: "${BOOTSTRAP_NAS_TOWER_IP}"
          path: /mnt/NFS/Tower
      mountPath: /mnt/user/Media
      readOnly: false
    nfs-nas-movies:
      enabled: true
      type: custom
      volumeSpec:
        nfs:
          server: "${BOOTSTRAP_NAS_TOWER_2_IP}"
          path: /mnt/NFS/Tower-2
      mountPath: /mnt/user/Media
      readOnly: false
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi
