---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: default
spec:
  dependsOn:
  - name: traefik
    namespace: traefik
  maxHistory: 3
  interval: 10m0s
  suspend: false
  releaseName: uptime-kuma
  chart:
    spec:
      chart: uptime-kuma
      version: 1.3.5
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.17.1
    env:
      TZ: ${TIMEZONE}
    controller:
      type: deployment
      replicas: 1
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "robot"
          hajimari.io/group: network
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
        - host: "uptime.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "uptime.${SECRET_DOMAIN}"
        - secretName: "uptime-kuma-tls"
    persistence:
      data:
        enabled: true
        existingClaim: uptime-data
        mountPath: /app/data
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi