---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime
  namespace: default
spec:
  interval: 10m0s
  maxHistory: 3
  suspend: false
  releaseName: uptime
  chart:
    spec:
      chart: uptime-kuma
      version: 1.3.5
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 15m
  values:
    fullnameOverride: uptime
    image:
      repository: louislam/uptime-kuma
      tag: 1.17.1-alpine
    env:
      TZ: ${TIMEZONE}
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 0
    controller:
      type: deployment
      replicas: 1
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: robot
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
        - host: uptime.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - uptime.${SECRET_DOMAIN}
        - secretName: uptime-tls
    persistence:
      data:
        enabled: true
        existingClaim: uptime-data
        mountPath: /app/data
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi