# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:3qbq2QpkmX+a3XL7w1ACc6zTdEoucqPGwA==,iv:5xO71PZ3ZJHapDRcIX+KEctdUt9Dl9/Ye4e/E64CeWM=,tag:ukNRrqtLqRCljHoy3QqJow==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ipQwYyHLjb+llMIWJp3DdTDNOGRo8g6o3BqGQpYyNAkT4l97tA==,iv:55B6rupD9AsW20Cr8566+sXlVB2hTD5MvVsRp7khI+M=,tag:gModK3pjhmj3OmzCUtB+5Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:EEQQQn3KrFeCYDmExsw0LuIZmIZK,iv:qLt3bUF8IuLs+1PMQTB9M+19ThY/L6Du8G9HXUXg++k=,tag:gntxwzkgM4YkxCbu4NQHOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WW8vQXBPbkJ5MWlxSmN3
            QjhwYVNPRlRUWnIyQ2VTaXdPSFJHYm5OaEdjCm1SN3NHUDN3K1VnV2M3bkxNRmVq
            OEVzTXRXZ2RpSmFOZW5sdHFQQnhhcDAKLS0tIHF2Zy80Vy9ObndTMDBNSUN4cGJQ
            L1lady9IVUtkY2pJMkNwWXdsQ3dhck0KGck7+BWdR6xYYDWByiRgkEfMJn0+gIkM
            3JMefUGOXL+iP1xmydEP+u5zFNyPaBEZ0jr8KyG5oGEH9D5wbwJBaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-09T18:27:10Z"
    mac: ENC[AES256_GCM,data:RSXPbtOagmlr9TtuZDtITkfTAV19H2FDyvOUTIxExHUprRETXxYzfk2oAKGY8OY9ssEEbVV+j1eQpWc9GsPyNP3ghRmo2FWS7Bb+ecBEWJZIpdG3Mj3t4gDq6Q/4iSjgSFkSvu5G1eeR30Ek10YqfbFiydOgJENCMuDdcrv0GD4=,iv:JCnCqW8lMrrFrKcyYItEvhZKaBnzenadgM1mhlleu5Y=,tag:zgHThWO9nlTVyw1HTLaSEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
