# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:bfc0dlYRz2MrMjvkEFT9/+JWLFlDimfS9w==,iv:JuE/66YPNt6XntQCwZ837rStlkMf320/zngasnGg+7Y=,tag:SSQUZTY7JfOZX9VCooqVvg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:CxhLmpUGlLaO2vkwfaEjRyivr0u+ABKKI5JG3hoCOc+HkxiVsA==,iv:F4UXbfL7lZmKyCFpjmcU9WUbcIVPUp684JIJTCeGmM4=,tag:KPZLfZeO2WGJkVP0GyTTIA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:QnSc1vFfHGhiYlO2n9pPEbvKk4HV,iv:kHuCG5U86afVGAp2Zx2PiI8CaDmEo/HEpv2F8LxfPH0=,tag:Zt3BeqKVszFx4rMEDUcZZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMmdGU2tMMThVc3pVOVpR
            SVV1dm5TRGJUL3VjYkx4UXJhSjQ0VGM0TUV3Cm12NlRLUUpMTWRGS2xVbzJhYmxm
            eDJDSXFMZmY0ZFBhTE5XR0R4NWQvbm8KLS0tIGI3S3dkSFc4Sk4rVGtMbWhzaVBj
            bldUQ0ZWOHA2cUVLSWp1NWhIdTBPSmsK61DPUFIh35ZN6vs4vaPCDokj1oK93fC1
            FNmZhYX7MitxejB/UrnKLtufMPTcckuc9ICWvh+6lmySZoILFGvXKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:51:24Z"
    mac: ENC[AES256_GCM,data:OAC6NDOiURUh50atFDJXbtFxpuhQJI6+laeNuiDangjWwtjB1h30CPzkt/orRJCEPOk4CyCylv5u0wSIuwDSH4bo5TyF94GfwYfLaqTI2Jnm0tPuSaGt6Lzy7uWJCjlxpgULGEJooFcf1zLfDjojivxjsX0OAcHkl+aKhuiZT7M=,iv:ZaCSC9VLGR3UaMPeGD/f7JutGW+b2N6Yxho8G87IQ80=,tag:tgQlLaD1zfpBa84T3MuJvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
