# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DLgCvb/6eN3KEcj9GXSA+jOfZsFTsin5dw==,iv:fz2sfArsbeQ94Ug0abhox//zL67oZEGBCbGnBdccbaI=,tag:sLIuZgRH8rPltB2/pb9EWA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:S1tNhaq3D3hgtADn9OZ1IDI3Z9e81+zWwBoo+7HJSAsPPPFgXA==,iv:zdE9jcoDvMgWCOaJdmlUoW8j6qjg4qmgJ3C4FbYPgzo=,tag:t9vzunQHdXvW9oQa3Zaryw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:NKsik4T8QCD7LN4ULdQDl69QfGKH,iv:lu2r7zQXBsxPFymVn+aQEbGZpoT1dInZTt26OCORzAY=,tag:RCtP+CnLubregrL9OLQqyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndnVZUmhNUnZaQlVaMTVn
            S3FIT3hnTUZVeWQrbmh4VzRHN2EvLzJRT0ZFCndQcGs1Y2hsS2dpMjFBNnlXRWd2
            aEduTnkzYytvNFBUa1BsZWdvYUVXajgKLS0tIFhxRWZLSDN1eDdhUnJIQnpJa0x0
            NjBad0liNGhjWXhYOWZTcFR6SjIwYlkK8AwVZPbKttf7OlJB9sMPLBF1YxEq5cuX
            cZdAxoT9Q/gb8JJZV/2KM/D8PJnHTpR5btpa9PHnHS3BRnDiXIwSFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:39:07Z"
    mac: ENC[AES256_GCM,data:NfkJ5eaV3kNHiEjEGyhpt28Ok3kPEzIapJf1wKeyy1f96Tssh4nLl7YTS/W4bVcPlo2cz6BokZ8c4koXtnQY9yns+L/b4DlBcdylIsQZbHJof3SkCGaFxDJnpCCEMCDUwyaAkbtETioG+zNwI+vVYdkQznjms09yn2ttSYT8py4=,iv:aVZB3SfThLAsCgaLwfn1JnhdjioEH87q6C7l+fgfIdM=,tag:GX1hywPz/7YtcGQAG7DeRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
