# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:bJ9ada+bay9E7D2+BRrMnsN1IXITogtlLg==,iv:zvIXeX42HrKbKKsdGxbXlZuM7Z+aHiH0LDu6PYtnAcg=,tag:wZZKGZNaweUp3wLbaOTsaA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:pbwYcvPxBo4An/kVC5ugp1qMd2EEjN5mj5Cf39/IJc6dxnPvLw==,iv:Df3w1pBHRPwMa1oIW+q7RCIZon/ICZMcD1fCU+K2Yf4=,tag:/Epre4uHCtZrn26/kaMenA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:D1ja3REDwvbLqSI1Arnx4W8gm+0o,iv:LMDqrZ+r8szSybEHcNWH0GH36qqXJUU/qXslyfWJNdM=,tag:v7fZCbv1EcoRhNuwrBaGKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VWFObmJtYTR5MlRxaDVK
            OWtpZ2x0RkRZaGpQNjlzMHdBN1o5UjZVRFNnCmNXUk5MamRBQVpYbnkwTCtWd1VC
            djY5TmFVS3dDWW52dmNVNDhYREJCYmcKLS0tIHgyNWlseTI0WW1zWGw1VnlTWmla
            TVFEcVZlSzdkekxZMTNkVkhJS1RSS0EKDUS5WmZEHYa1Bwo6RwDFdl86V/ErbJWS
            ECdNO0nA+9XRcLklR4Rr5JaeHxgWk6BcACH3xLo4TfXP1VIdOVz+Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-09T18:37:17Z"
    mac: ENC[AES256_GCM,data:4ZapR+w6u0SA9PrOPpcaITCRKy95Q6MOOjA8kX86QHmyTHL6+YEPUHFf0AVra4chhJBa+dh2jtMaLP74PcwiM7xQadnI5zEa4C7K5KAJIyuM3Ta5ZCTTUymzQsMcMua6Jbi7p0XZGXzLqs2gk9Uu1ImXWf4AmE6ojcx4iMh+FB4=,iv:zRxY8leBOAQgO20N1Kjn3PhhmBjXq/nYOhSaIBs+aBI=,tag:eHJ72rB5Wfy5Hkhp8nJvWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
