# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:aMq6xctFRG8V45omeRQlE7fL4jx6JVzeQA==,iv:FMBBAm2WlO2bU7XF98s/DxaRykaqEMDu/lnFnBtd37I=,tag:OtIvw9shS5+ley6wxSeiFA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:eo920eR6DUCIp7UU2xRJBny5ImrdIzUbJ+i70i3srjolAA4dRw==,iv:O+UO/+KAKjnbBje/ecYnq/Gd7kuoxgKlnha7pnkh4M0=,tag:1L4hQkOjGpetho813iJPEg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:gZfhSo9xd7AAIiRyZDn4KpgkWLhn,iv:W3aGEd7YF0tJa65HtYqRoeXQ7NpDScjl18/keB41MzI=,tag:ORmz54U+rSbTpj3RgT+GSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb0dDOHVKTE53Rm9EZTY3
            d1pFcDJMVmZuS25ZcEh2Z1MrRisvaFprNXdVCkpwanc3SXo2NmRxTkdOVFRkMlpw
            WS9FRVNkZ096end2b0pFc2V3OExIRXcKLS0tIG9SNEFDazBSTHJoN2tPdGNxTldM
            UjlDaSt3dXh2UlhLZ2Q0MmsxWURLMUEKyUEjCzd8A1gdPhg7iS/MfzyEffnoBBcD
            rRj4oAlOoQqgeofVIgSnnua4AOQ/fUsLWrAiJyPwMoZn29jrEP4GqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T22:41:03Z"
    mac: ENC[AES256_GCM,data:LsOWecenLXj39E7QyiOW1IHVmtdJp0k8XBNnw2bpgfF+jqricGh3Kg1qRaxKTpmGvf45OAggSYSUc1uMmNEg0dLDrbywyhnnKvoAL1dro/uMaWEh2qGhYx9qTwiNzoRxrUcKqcVZ2k/tJrvbbKWzwG+prRnqTHUj+nWj2zH5/Wg=,iv:P4oAXDDm3L4xls1LQ9o4cf9HgMO22VO4sW4JD3NCByo=,tag:X2wHQRSP/fxjcTzYDPvQWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
