---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-system
    - name: node-feature-discovery
      namespace: kube-system
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/jellyfin
      tag: v10.8.4
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${METALLB_JELLYFIN_ADDR}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/jellyfin/aquamarine.css "></head>';
            sub_filter_once on;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
      tower:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.7
            path: /mnt/user/Media
        mountPath: /mnt/tower
        readOnly: false
      tower-2:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.208
            path: /mnt/user/Media
        mountPath: /mnt/tower-2
        readOnly: false
      transcode:
        enabled: true
        type: emptyDir
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 6000Mi
