---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - goldilocks
  - grafana
  - kube-prometheus-stack
  - loki
  # - mimir
  - node-problem-detector
  - thanos
