---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: default
spec:
  interval: 10m0s
  chart:
    spec:
      chart: uptime-kuma
      version: 1.3.5
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      type: deployment
      replicas: "1"
    image:
      repository: louislam/uptime-kuma
      tag: 1.17.1-alpine
    service:
      main:
        ports:
          http:
            port: 3001
    env:
      TZ: ${TIMEZONE}
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 0
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: robot
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "{{ .Release.Name }}-tls"
            hosts:
              - *host
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    persistence:
      data:
        enabled: true
        existingClaim: uptime-data
        mountPath: /app/data
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi