---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: default
spec:
  interval: 10m0s
  suspend: false
  releaseName: uptime-kuma
  chart:
    spec:
      chart: uptime-kuma
      version: 1.3.5
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    global:
      nameOverride: *app
    image:
      repository: louislam/uptime-kuma
      tag: 1.17.1
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            enabled: true
            port: 3001
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: "robot"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        existingClaim: uptime-data
        mountPath: /app/data
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        memory: 100Mis
        cpu: 100m
      limits:
        memory: 250Mi