---
kubernetes:
  children:
    master:
      hosts:
        Master-01.k8s:
          ansible_host: 192.168.1.110
        Master-02.k8s:
          ansible_host: 192.168.1.111
        Master-03.k8s:
          ansible_host: 192.168.1.112
    worker:
      hosts:
        Node-01.k8s:
          ansible_host: 192.168.1.113
