# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:8aQHP/NFIDpAYgVImIJwYgxYahqyGGIHsFyMmepnaX9VD3K7JA==,iv:Cff1nehwp2YvpPb1sMy9rCpeUPnJM9A4+tAPWS/bcZI=,tag:09MCtZH/aO8g9l5iagRLtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWVpJUEZ4K1ZoSFNDS2Jr
            V2JMakE3MG9lNXhjY3hDUlVHTTBQcytHTFNBCnNPU21Nb2c4T1pOY3AxVXlrQU5N
            VzNOSlh1TU5qa2Y4VUM2NjJLaUZaVVUKLS0tIHZJT1kvRWtWVDRzYmVBUzRJMGx1
            SWZQaXRnQ2tzQlBoUE50eVRTTEd6RjgK+wnG98WsNuBO6v9TsfKrNhlPpa/VVz9g
            0+El2CEWqDGcAcNtQFKoS1Iul2l5xbLib1PiYvcO1quGOG8ak0nSow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-10T22:32:43Z"
    mac: ENC[AES256_GCM,data:q73mwFSt9AuJVEogBuByKHAN7K2pGAuzVMTywjyK/yOR93jSnLgT5Je/el9+rD6qBXES1O+G1V0miSoC1119h+ivFZx3H+ltlBlAZ1WMCubuTo4ZQ24tndYMe5+q5hcAlw5+PW5A2K8NehFh9aIa5j89c+aFEnScrlbT63MhA2A=,iv:6h3/GbGVCKVdtpa43kUa8kGxoWykuC1iD8cP6LVxWyU=,tag:qeXrmpUumyanx3MCF/mTPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
