# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:7wQYDEtlHweFPJcBJntAhkcbQph+MQAeLS4KRKrB1vY5sbDIWA==,iv:2m2ztDpKjxPJrdEjvyzcXuErpNjvcDUsequv3IzLdh0=,tag:b1ktNMfmEU085WGMAv4DzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdkZSRDlYL0xvQm9MQVZr
            SndNd2UyRGxWT3FGM2grQUhBK3B6a1dFRVI4CktGRzZyWmRvN2g4SHlwVk1PSit5
            dCtOMkFEMlVjanhsandjZlBRajlNZGcKLS0tIFhQN2dkVEJWdGZWSjcrTVN4U2FN
            TWFTeDlJTUo0MWxkN0lSOXRwWGN2ZU0KLPzdmJ7OmOJccBDemNv/X9Iio8ndkSPt
            5epqjzJof+M8lbllsAZu4MrCwxyc8FCIT7uX35NoYw1FN+ZAmCLAgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:46:34Z"
    mac: ENC[AES256_GCM,data:rj5iA0Y3iDHAiyYRnMEFwNMeyi5566sjOy480J4e/OAvkpTJEfjP4rrAGy2gjKp51THE3/wF1CT3py712dIkxJoFsFg6JIDLgK+jmTyqO9Pa8XrZJoC463W7tukn7PWCviNjC2P/0GOnOzVNasPq8xQiq+RhugROlNRJx/qqOhw=,iv:hot6HwOaoShAy/VFV38S/3h7yX3xEvveVZV/p5i4mkk=,tag:XcCkpOPqiBbob1J3gBxsTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
