# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:V4FGNncl2G0wU25xGarTSI7/Asr/rPusU0S/8oz/WPgFht2MNA==,iv:jQ0ADnKhqa9lF+yaM/Id0R+cjWiNdQF4W8mIDcIza5o=,tag:4SC0UrKfmaftG2YzYSEKeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYW5SUldHN3RSanJyQWhS
            Y3hieFdaTmNHTDlpZUUzaEpHZmZwbWR3alVJCmloNk9nRFVwRUZTcDM3YzF0R0d1
            djFGVWt0M2xjTDFDdHZRQnlxYnduaDgKLS0tIG5yNWlrZ0wvY0hpRGg1U0tCN0hY
            QytNblEwc3c4bW1Nc0c4YjVRTSthS2MKfgCs2d7rqJAtRXTFr3pTEafxRTI3vhV6
            kfw7UX9psW0ml2wHZ6iaZEPMmuRvyumqIhD38+RnM715qIkcWjor8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T15:03:40Z"
    mac: ENC[AES256_GCM,data:1RgZhcGDIM6ZS6b3lLaLDGLK+5pJOoPFcaXJEKSn7bVJto/qvaxP1j4t986wOKVX79y4isPzA0lthsuj2M6wLOOrh/CVm5R6c99nX58FK1nkYX7qv0autBOmY1PkFVQ5IC0frOBz6DE+0r79pI6x7pdpKGuAJWPttpuma7oeA/Q=,iv:lVq8+uL+oKCGhgyyKiyPJ3KexYPUT3igjkd7Pl1AV6s=,tag:u3eCKtG3jR/5+GI+Ozwjaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
