# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:OL1alM0Y1SznAjiXdYeA4++IiFE40do6rwroBaVoclJOriSNXg==,iv:ubYknXGqpeZdnQ4/Ykb5TVmv6AvXLcANiDk2NC3pvnI=,tag:hLnxXNdfaDypnD9b/OTHNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MmRPNVNFYUtyU0NnMTlu
            ajV1YVRwZE9pMVV5WXNUWDRISE1jSm5PSFdvCnBFazhUNWR3UHpFZ3I1WXZvMUZH
            WW01K3pzbExCbWpoc1dKanhvQ0pZbEEKLS0tIEh2L1grZEIyWXFZc1hidjRDZWZW
            c3hMdEFLcmxWRk5mLzVNczY3VU5oK2MKck4WqGn6TILEr7Hp9ob4jXE037R/84sK
            qB0olb+FNwrhXbLg2k1vmliD6PfHnMs4oHQFFhMCIcXNQnbltc1bbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:51:24Z"
    mac: ENC[AES256_GCM,data:5HYgsqxKBcJ0rtoC/4AqapxjjK5UCpR76yUx4LtM0fiMkWu906wvgEi2gYWah97MzMcBRRokAUkHpN59z1GT4byEanrqBbemWAGEipCEREazZJe8pqOr6snU4bRooeMC2IMk6jOXEFWC8wt38B/CSM1M4fCDtThvF+Lfi1T6fJ4=,iv:/T5nSwjHGD8OcmRfaT9QkKStZNsR+FuRBbxazaRILI4=,tag:F0xXloMuf649mckKKjWlVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
