# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:nuqWHmWrBQoCa2n7vBEbP76AG3kGVn2H2k+ikB6ohaRgTipqCA==,iv:zrY3GtXAwPDzXlv40SEVfLlV2HXsny/NVBy9/nDxQo8=,tag:sshlk0N2JHCZ3DOcgqvWOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NHh1STFLUGZjZG5QQWo5
            VllEbXVMVEpOZGh1SUQ1RTVub0thQWFJN25FClpyd2V2ZUttOW5aR1FMb3ZVa0V5
            WUpNaW52NWNua0FIeVdCTHM4Y3M4S1UKLS0tIHRqQkFpTUpWbURiUytXd29yZnZm
            bHc5TDY1bytUdVhMN2E5dmc1SEdUalUKQv6k/pCxwAXqRyg0LGhBTl4saMw9qDmT
            gA8HQjea8G4fVVkEBk+tZO9mdt9d5FjWmdimBzP7DLm447kbKxuO4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T23:25:33Z"
    mac: ENC[AES256_GCM,data:mcZkcOaZkXcoH+AiMIN5Yotb3+SwA4l43ThzoYVzzQ+yKazYcTECZ4bxxeNFfxsOiIiblnDiLXx3vvyRexvTIEvs2YQDOEQQRkM4zCiJIK4uYBqekCur1y+jG/lKlpxUNXvBX0iav9dyUW1oKeyoogAo+hClWCjFrmoupilp/rw=,iv:+Xlm20xuOjxLmm7UFAv9XFFHxBwBfCR2XsHIHGv48fc=,tag:RTIZWGQMw4mCoRwiRlHjnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
