# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:JVtxXn0+X4+A1d/1yjdJmx+BPJPv2K/HxA==,iv:qEHZWltTWCqmOQicMtiCksxjc66L/wK3177i6QZWqvg=,tag:eJY+KCwtcP7hIG4QlevslQ==,type:str]
    api-key: ENC[AES256_GCM,data:PYfaq2STD6e2ghUv8RqdcSd3SQi3X8EZgD0ei8SvCK4RMDml9g==,iv:MyqRgcosBH1dJyyQ7oUUCYyje8tYYrJ7lgmrM/3hDOo=,tag:oWMpqZ/U9IbpOntYFt9aqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdEp0RTJVQVg0TUJ1VEZY
            NWhHdWVmMWFwY01VejlnV1QvN2hLNnloVkdvCkpxRlNCdzJUbXEwMGZzK0hCWDhI
            cmxObWVuMkNkN01HSFZBOTVobUlkSjgKLS0tIGlYSjVmS2VSUEt6SnFHR0FOL1VG
            NDVPT1JLb2lERm42VHdESzZFVEJmNlUKamNrTKX22LoFsyPLx8gL9C0M1C2EcQFu
            2i1JH96aGHG6475OFOC9nIoPRwulOAGnwn2/3dA6bd3wmHpLxBQ+Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-03T21:54:40Z"
    mac: ENC[AES256_GCM,data:eb4XACh1frppL3kmI6SYw7tBDFNRrqDQMq7DdTfWs/rOs6iZhmKRYJ5G69qGvS05qYexlpss6zYIgEQn9igFhVZRzOTtoqZQmi4m78tSI5osp+OTpZSGfGEgzzzxfFUdU2Edxb9xOBx+ExNES4wk8QdE0rgmm+lmixBGQpt9XBc=,iv:DABnp59l05FG7CDAYfE50CYynfxmVF87Qxu/CWwS6wE=,tag:muunzspJYnl1Zw79tFZW/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
