# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:YDmhi4JM2wYIlfL7oKpmYu4tLUpBRwxixw==,iv:FTwgvtcp3RRPESrPP4kgNr2q8ixYXWgXxdaUY2egxtE=,tag:o7N3t+ET8zLYRAwF2s03oA==,type:str]
    api-key: ENC[AES256_GCM,data:bstCBlWnNnjKXdIiF0fsZIWGEF/CPxdO4ZOkG6DxSHbkO3oA7g==,iv:kXXaBWvC11Ybly1dFwfV7nv0QQdgdKHzsdZj3mS0hpA=,tag:PNh3Qr2myn5dBrslXqFRiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OUFLWThSZ3NsMkdSa1Ey
            blNzRzVrRWZsWEt0MUhBQjRlRzkwREUvdGhNClNnK21BQ2ViNFZ1dSsxeWRMMEs3
            bDdyMEQxcGtyWUg1RUJXOHVrU1p3NVUKLS0tIDZpTjN3SVV5ekZPdzRBTnpDMGpm
            TEpOUTF3dURncUh0WVJvMTkwQWpJWk0K13DOZPc+RD5/Xc7e47Mg6Ky0amZCOOoU
            +6d9aH5a6HnuWIt7zLGMNoA23H3j7Md9N9UdAfq27x9KnJcUEPJHyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T16:23:56Z"
    mac: ENC[AES256_GCM,data:0HgeI/LcBqXO8qgDiIVJkxvxffTm9xZesCDc3+1eGwaR6gKRJK30U8sqWoKyCia+bUVHx+yAhV2Z4Ttj3YulEX+/n9F3vRLJ9ZSkuF0D0ftykLoyjdVPrwTbQr/0QxOEr6CPNtHevzF88GZvnbOLoDy3ZW2D7rrfyosJLothn1I=,iv:f5iO8w2+5T9KGWMMyOTMtleYUrfXlwN/fogBDZUS/6Y=,tag:94LqDUmFvzzQGgigsG964g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
