# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:F7fqET+A/LPuqU+jAU3k5iFEvhw8a/OW1w==,iv:veuO+tkA2dcUUZ7olL+z10OWMDDMFOp0e6Df1F8vMiE=,tag:dePrdRB6JMxzmQL2WZ4SJw==,type:str]
    api-key: ENC[AES256_GCM,data:bnWv9d+e6dQzZGFQHi5XOK2v82M3+0iXp1AEMabs/tmGaJASTg==,iv:POxH83Z0+nHTn4f/Y29926Qv0XAWx24pOioKOgpq+ug=,tag:NzAf2hbbOHRUmfVxHKW6DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TkxidWdMZ3BpVGJnNzhE
            VVpnQSthVnJjelIrTzd6a1ZTMCtEODUrcERvCkxiRWwwTGhXOFljQzgvK0V2MVAr
            VlRoUTZCZEJtQ1JGTnV0YW4yZWtuY0kKLS0tIGhLMzlVb2NOVG1QKzMzSE9vNWs4
            TTBLdDhUWWk5NTN5UDRUVlRRNm13SVkKNle50suTVILcFQIMr5Vt9A91ny2+quzq
            vT+qLRp/DwXoWnk8+KZFriDQYZv24rKK/hH8RyM/nEbj18UirEi/1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T17:28:30Z"
    mac: ENC[AES256_GCM,data:ml70jmiILc9/QmFMdIZy3ag9foifELMEdBvu9DhVEBzEthSAkNCpIz+vT/xTg04nzRieQihqSVrkQtPGRY35fuKXnlepI/0QFHb8MFSSIdOxK2Jr+cU8a7rE5dGYtqwoFUh0PEa4mndZ8QDS0yhwohx2FTi0qJ90Ej0gKnH+ALw=,iv:Th1SFETZwdsVliSq56LSPZLdggxJDfzdp6kGKQPlv7s=,tag:muN0MXDEUIEGHHvttPFQcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
