# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Bc5QOXqyjtYbcP6kGQ9QhA==,iv:p9Max8ZkvIeOWTTi/7c+YdlhAU4QvzZeVRA9an6nbsk=,tag:QckxRqhi8kRwirzi5JEEGA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nk+C83SkURzD44h2YX5jjCT55T/cOSVCEg==,iv:41CTCaBEKFDFXiAf9YEnKuTm1ionkV5JX+vW0Ti5mCM=,tag:h/4RZUo+HMPjtzNt5z8IeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RlhuZlFOMytKdnpZeTJm
            anhKdUJTK3lzMDRrZVF2RXo3RVFkRzdsWEVRCi9YdlZIN0U3cW1ORUlHV0Vid2xE
            ZXhYd052TWNBY2VRdWxjOGFuL1A0WFUKLS0tIHhoQklzWlFIaWRBWDdHbGNzTC91
            UldyTEVGMGFDc0tpdnFoUStsQ1Jia0kKomrYmowhPUOEs6ORzvucoPbAKa083RxA
            bMegdfTTxd/Uo8UIyjsK7IUGSnl0SuhZfBxQtNMtsav+pQKryI4jkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T16:11:54Z"
    mac: ENC[AES256_GCM,data:fU/g9EbcnWpT7L19iGiwEww/KpnQCPjxLdrc31cmwhwXy5LmwE0wD8qtyk0deHYnN2IKDA3UNyT7Rc7Isg/6L1NJgADIRflG0Wsx82IDTVDHVRTwdY1NWLw65CzHuTdlNVu9ZRlTRzLEC2HNZFIx8H6SWg50Dpw89Bh2Y2K/wRk=,iv:dXKD6vXRyZ60Zi5xyjMLKMTIe+zcm+fuNE+q2pcwZ6Y=,tag:zWtQNld6cEQKkInPL6qTpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
