# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EyVgPdqERSJVmmZy1zWFlQ==,iv:wNHc/ZIBBIXYEXDAeorhRgif5V+Hz6I+dkz1mlpBe4Y=,tag:9rxY8oo5g9YAKnOvUd2WUQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:r+xj5AxKRdID0wU/pkubaJHRDwFMHHd4yw==,iv:+CwOtX3Mvgjkkf9eFCtt9VyimFz21SGJThLLVVUrhRA=,tag:mKQn/p9Sm+LYDfE1d/M1qQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWFZEem5Ic2tJbW1zeDB4
            N0N1VFJlbFVHRllsdm5qNk8za1BPc1QxTWg4Ck1HL1Rsdk5OUkF5NDZMVmsrL1pI
            Umc2M2dja29xNCttUmt6U2NiU1V1RlEKLS0tIGZqeUR4aHdMRkhSUUJiZDdtWGFj
            T2JWVnV6dm1IVll3dHY0eEFzM28yeTgKVdC1knfTY+AT2YYx8T/EcxhMuUjEAivQ
            R79Ecx4mqcEggZi5CtbXpmLh+Jx1dRKs4a0WrWjErphIDoSiGj+NyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:39:07Z"
    mac: ENC[AES256_GCM,data:wyf/StvjobFTe/19tB6hnCAbJw8SlJ/bko8j2C87xHKOm0ImXKKJWiueKFyoDPV7lKEVNmozPGsQ5x5Qh/1PDz6VMrFMn8T7hrQN1qUrTjVIj6+SB7Kh8XO6QI336DVCxXYO7J1QqkK7vWRYcjqnzG16IjwNvQVxz74Po/lZ9MU=,iv:jKLWFYiJ7v5ADmp9yvCKRbRIMVdcN6LB/887BaIZtzQ=,tag:X7bihkSw68E0ns/4HFpGPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
