# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FEweGL52o9O53lzhcvM83g==,iv:E8OnMnEvtxVUXlOGM6Jd2Cqf2ZZ1otwIar0TA+dDJ0I=,tag:Gc9XYJfRzPs3cQylAALg4A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:57pN33QKdD70Dl0Jb4Lmz9N6zF8Dwh/E3Q==,iv:xVc7oDLeFSrcE2vJ8o9edsnPnfO5TJzpN8h64bL4aCU=,tag:bUVTl0tz/qu3yM5lpJreyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVDNZNUp5VndyVXJUV3NP
            TElvc0RxSUswY21kUWJSUmZTYW40alV6R2o4Cno1Z3I3YUZBTU5FR2ZTY2FGOFNO
            bGxvNWlnQ0Jlei9WRmRUSW13WFhyUXMKLS0tIHVma01GSmQvYTJXMWJaakdHU0pj
            NnkzbUZPUUplRDhUcHQvR3NiMmRMRTgKB0R//bpB3EhCaJzRziQdIH0ItAhfuxr9
            7ww7oBu1tMcWyqImE3kYByK9ZXpuK8BWyyBoaHeGjl+L+mEc5ZMKSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T17:28:30Z"
    mac: ENC[AES256_GCM,data:n8BkFPCJRNmNCuh+Xag/ZQxw+jeJVeKTJPplmmhil6DcaOZpH8+YzHjPtMjHy1qWuu096QvpdUJiqjnccwZjVYQgM3kuxdwlXT13XEy+8pnDODkGw89jD+fxtl9jgmMgWAE0O9lQF8R9YBlEiQZYozss70TGfBowv9dvdM1qG18=,iv:kPapQeVsu6Dwk2/VvDbKuDj5kE0K1vGMMCzuoB8N2VY=,tag:wfax43DgkOWKuIg94fasKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
