# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:d5IQLaCTM4MZCTiLYRO4Rw==,iv:S1z0uUCqb5Cc270gMuTZri61/NSFOw/getaKKtWbsSU=,tag:H+y0am0GSMAUaENnnBuJLQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:b5vb5lQcVmSABW3Mjzy2sNJ5T3hqN5K8ww==,iv:+vyCQ3WJuRoPjz1Bnwivz61MpV1YWmN6Ft4qawxd5zo=,tag:7C6cA510jipYAd9Kd2GN3w==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:ajf2nMs=,iv:ec8HSwXKQ9fN0bWqcQo+rQq1o2uOlNdFWiFCQ0Rzttw=,tag:oZ20LVckPi1TBpNWPMc2pw==,type:int]
    NETWORK_MANAGEMENT_CIDR: ENC[AES256_GCM,data:5yyVYx+IqWZdC/ddKkM=,iv:dBVN3gZWcYCU46Zcob2CWn8+1rf4kMT8Ha9Kd64HnuI=,tag:8L0OG2tHr9caJndQbAIaEQ==,type:str]
    SECRET_VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:IhSqzN4=,iv:vZEWE8OrOvxDW8DHKCHYb7DtO07AXwSOWfrDQIlHiWM=,tag:KgpCONhwXFi/lhJWRH1d3g==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYWJIVC9iV2hQVVpRSEkr
            Sjh3TnVZRDRhVWM3ZkVWUHROYnRsVlpFalY0CnBFb1BJVTI1UmJXNkZwdTJGZTB2
            N3d0cEtycmZjNnR4SlJUYnFyd2NjU2cKLS0tIDhOU3hBM2xMeUNhMUladFFqNVNI
            K2FZZW5vVE14cVJvOTIrVHU1eStVcXMKBw3xyIKMGuEj3oKiXZDjYruAx+Wj8Zqu
            0UeZZk6lE+bHOBdeZReZ5AJrhQwG91kk1e4pv76YXyUhhKdwxezaQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:44:27Z"
    mac: ENC[AES256_GCM,data:DK8KvEoF+Z8H5NGV0IunbPejJ6oO+fDDn3efKZ1yAlbBoQ23CatU84Y3a2sCLEb57WnVnRm3jD5PE6yLTjIZfw6lI6JkTgXo1fqnqk4bM3OjQ+7k5KebHUSwhmgXErnu2PCRsKRjxo1pJQcjO/yNrff1wi2n/IFL5tA2C+W0sjI=,iv:KHA28J8llpU5py661MYMRGhj2sE+tPXy2ClbtpbkIYg=,tag:WUWtg/J4Nc0ewjTsmFvp6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
