# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:TKvNSr2m+X3ZVw0QNJIfzQ==,iv:m5EPIX5WxN9NOGG5krf5du+5FfebwSA1vD6sgLuMWys=,tag:cx4YVza+BKZrrTFFXtdQsw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:BOi2Of405rs0Kp6wPj3ZvGAOZEEplM3zDw==,iv:yL7Vx+QFCLLepd77B/fgG+cLmLsTWFM1XUfuH4gnR3U=,tag:TZ79YkbQjKcP7LtGMgP6lw==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:8iAMEMs=,iv:37bSQcfZE6L7F36R6NjJNtmUjYmQVJSOBbHDw/hhdE0=,tag:VnwouDeFGGuVy3NErxbKdw==,type:str]
    NETWORK_MANAGEMENT_CIDR: ENC[AES256_GCM,data:3RgIXRr0xjpq7UNUznQ=,iv:qeR8/eavlmRJTPoG8ze+lerv0A42rF6znZ8b+udB894=,tag:l+4ReLfI5jrnhA19ivfDPQ==,type:str]
    SECRET_VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:kmvUNZA=,iv:QbT83gf6smWzm86ZpFCYaMkmQmoa746nwZ71FlYs5Dk=,tag:R04896/iY/+Pxgq6YFuYaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQVpIeW1CbERVc1ZhOTVs
            c2NXQk9KaEVNUGU0ejNvMUtJYjJTQ3NqR1NZClZQM3NDY05DTFJQb3hWTUxSRWYy
            cGpnbnRlUnV4UVZBOTJqeHdiejZqSWcKLS0tIFFHdkdxdk1obk5uVDRtS0JLQ3dm
            Q1NLZDU3aWJOMTBrNXhIK1o1SnM3T0kKnXTpLkKQjIww7AVuvNtA409MNsyEVhxx
            eb8iEWmE4+/F0xuAmBQe3RjG3uZuFpMayrBvDpiNVuK/JZ6TdYrE/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T23:19:36Z"
    mac: ENC[AES256_GCM,data:9cc3A1oNvACFZfglUQ0b4ous+ND4+oCqeo6tH/vr9sy6FY3yriJw1OOA9sjiMvxxQ5YHi6MNXCBsJrOCNLDh+vjJYilQe0xw7XUVQMl7/mmL6ooHMZo5z92Xkde7CbmNTtl3p7fm17BKpgrFwnoo5qUEbX2IlqRbtlaOgYpBdwo=,iv:W9bi8ZnlNCRETp4go8GU+cToFnfrT3DUWcYnGJCe7CI=,tag:Av+jJ4+fIoVFLbUhZp3IIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
