# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1rx9whD7+iOcqYNFL3NPHg==,iv:F1/W+30T37R5ff706yychwmMqxaJ+MYNlE4uBedkl4k=,tag:3swk71G8CnFRA1M8iftetQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:p2oye0DCIF/qDn5gixIt3F8u6J8pM/UT5w==,iv:TxYb3tzFKSkPspp3Kl3LcN9s3cUWPQBIbc4JE81xv6E=,tag:E/ICU4dwONdPgLY3Mc2x/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdG50TW9aSkcrOUVHbkJ5
            cm9xdzdXM3R3S3k2TUhTTVZRTTU3ZzdoaXdJCnZJbmdUU0pNMFZubjQ5c0lpSTl4
            V3BDc25wMkpHT0l1dnlmZTBsekRjWUEKLS0tIE1zY09WWGVZampLaHpGMWR4b1ZY
            eDhkVjNDeFhVVzhjMERvMlhWMHZWc0kKJNtOohdo+NuqMulkCdxfNmltH/iSku6M
            4yPrYCH9Eqz2uICFdGzE5WNgJa1LicrmDqSp77V1Refv5HdwSFja9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:37:57Z"
    mac: ENC[AES256_GCM,data:tbUjgsXmrpzTdEgHWVbjiRhx+2Ou4NW5NsaT8pGxt5hehj0iFeWwS8i316rbDpalkx5k7WmhuYkDbhLxH29TNdiSM8gR22v79eqSVCZSZzq19krLTrcpgEIZj5SQdFvt03lxvvn7aMNHOk0c1sniS9q6Z3J2lfRoU2urr5ruf0c=,iv:Ud0guwIPSVH9hGSz2BQXneb2kYTWztOTDSkj12YoLdI=,tag:vnpCRDbT8Ut8HzPc2wAflg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
