# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Bc5QOXqyjtYbcP6kGQ9QhA==,iv:p9Max8ZkvIeOWTTi/7c+YdlhAU4QvzZeVRA9an6nbsk=,tag:QckxRqhi8kRwirzi5JEEGA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nk+C83SkURzD44h2YX5jjCT55T/cOSVCEg==,iv:41CTCaBEKFDFXiAf9YEnKuTm1ionkV5JX+vW0Ti5mCM=,tag:h/4RZUo+HMPjtzNt5z8IeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RlhuZlFOMytKdnpZeTJm
            anhKdUJTK3lzMDRrZVF2RXo3RVFkRzdsWEVRCi9YdlZIN0U3cW1ORUlHV0Vid2xE
            ZXhYd052TWNBY2VRdWxjOGFuL1A0WFUKLS0tIHhoQklzWlFIaWRBWDdHbGNzTC91
            UldyTEVGMGFDc0tpdnFoUStsQ1Jia0kKomrYmowhPUOEs6ORzvucoPbAKa083RxA
            bMegdfTTxd/Uo8UIyjsK7IUGSnl0SuhZfBxQtNMtsav+pQKryI4jkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-03T21:54:40Z"
    mac: ENC[AES256_GCM,data:ug2IvGEjcaIT8x3ZvxiKktCQN8jsIPG53lauvnX5cHChEbQ7PtAXJDimv3G9ZIcCJ2vFzpqx5fr4kXPKAm4ue9jLFeq5/bvfRXswNzBRe7Fd7/6z8CtR1XfspXrkQVIMrxXReX2otyGWfsUGo2r4bg0Fqh0uYlOlvy+eFWTu0tU=,iv:TuzPpoy/TUdyJMBvH7bdCgOTfjKKiwDmvogU/qzXj1A=,tag:VhCNbLkuZmcPfajBA737aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
