# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3yqUTrhCt30kMhSAyIpJnQ==,iv:tSK3jSJMoTI+D6Q+ihXtzmvb76s3NCjMO+UvE+ILaPo=,tag:b4vPARUPJc5rRSOXc5s9VA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kqjFwMB8veBVLyBgV85IZrn/ISTtOVIgyQ==,iv:BPuJchE5s3JnurlbgwANNEp2yUhMSmX8SEKI94/86J4=,tag:DneI4WWKqzqjQUXXQ9vw1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZ2ZibmpoQVBySnVCRDJ0
            cUZlTVdaS3Fzb0VDV3NyZEFoVlNGTVo3T0R3ClFwdHBIVTZRS21TRnFMRGpENEYr
            VXVLcWw2MnJMZE1yMzlKcUx5RWQrQW8KLS0tIGthTW01UDRGTHlXUkZTeFpvS3da
            NjEvdkk5c3ZoRGlvTDllSkNLU1I0M3cKo/fCXGO/s1aZw6f+bkobiHRSQrazdGyL
            dS2Fx/qjk8zGBFMnOGeA7K+dQGZV1zKeEGYtviq0xEEiXiXKvAQCZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T23:25:33Z"
    mac: ENC[AES256_GCM,data:Ga7JRv6c4uONQtvMv5E2hd9YzIU1OOafZQuFqCl+qHgJcoKuAjn0NGJWGfHXEdlfJs8cWGo4Q5714IqiMg2yEFKNEOarlVM+G03R1geCTbLU2NiIqh4h/oZ51KygM+OIRTEGb1/CIT/AqHPrUXuU513z0tGIZAdxtT/y1PYLCLM=,iv:l8cOsydnGhjurGhD4qP1XokotlIT1Y3ucRVn9hfSntY=,tag:shDxzfDWpVDMgH7Oqevnkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
