# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hWkgdfX0Q3is3tkpYHZrvQ==,iv:HQW5jRb9HTogWAcbRKauxHsZuRQLm+XF0e1vdg0YpkE=,tag:z7kYbrMrbtjcHkrYex7sVw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5dqZRhqgWK8DsIFRuiLu5OSQL3hI8ljVow==,iv:yC7Td03Y1Uy/EUCEcUuJZw/7y5J0P2qa6eWuE1srRTc=,tag:u1aNs7ym+3ElRUpKBdVJrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUTRkOXg0S2k5V2R3MEZa
            OUdnZmN6MlN5V2VmQWNnM1ZSa0ZDWTkrWEVZCmhLY3hUOXIweCtyMG9VbHl0NHlW
            c1g3SEVEdXdtRW8wd3VzRXNmRmNPUUkKLS0tIHhyOElBQkJvcEs1VlYzOG43SU9i
            R1RNejNQSEJEeHVDeTJyS3lzRUFRZXMKs/81gPkhEKTQ38Ty2ACy+vQ982BSbz7c
            Zii+BNbqxLjpg5YDE0t5FdweRQ2dPDbppmAlhK8ymINgwkTESU02Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-09T18:27:10Z"
    mac: ENC[AES256_GCM,data:GAc/1PiRKVVHDsnw4Wo+lYDmgsXOYrP83+oRqRUUTRf8dIB9VoxiEWFzWJOZwR7snmQ0Tf0HM25XVfNhQQ4pn+sFqUeaPbQUxHC4MFmpnSkOLdZAaaf4lf3Vr+HQSp9cVs9ckcHJ9wRMpxb67rsha2z7M6P3EnfkjCTlS2z+GWs=,iv:jxBdyTrA9DpM7E5q+V4LCBlbA7pNlvPzvJPrMbRkLCA=,tag:Y4BskopWoxne+n0uhVZE+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
