# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:N6DFJccUtilDU0DzSSdX9A==,iv:RfsHxfSJRMB/cGEIpfkAENuwTM3M3d2DtRco8klMj5E=,tag:OLZcfVSDdCgegHWaIkxFcg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2m/jQbHhpfmtQytiBQwzG000F2OcLAQlUQ==,iv:2/NJ8NV18VabyopFHKMAJr4BJzsXfuQ87kYaPACs5Ak=,tag:oGxpLKg/mN5zo1bmWfmEkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCci9XM0drU2I4cjhvbUhM
            NFdxSTNLUEs0TWtFK2tkMEoxOU1rQXpEdncwCkE0ZjJRemtCSnB6dXFDV09URWdy
            aEpaeGZGZm1Na2JuMGpZeTBjSEJwQzAKLS0tIE14eGlnNnRBRGliZURNeDVLMXVl
            RS81ZkdEcXp3eThlVUpaVDlRZ0lUUFEKzxNpPjxUdJcEUiYXQg3wrQi9ah3LwlZc
            7CdVoEJHgIAdHo8CdFS2PvsIkrGXsMNyJRmoxSf/PNRexJ4DPCHArQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T22:11:11Z"
    mac: ENC[AES256_GCM,data:fQupW3BfjeCmxn44Xs41coc/RdY1nfTRR1OKadMa4bt0t4RTrD5dbZjBKtHiF23fS89H3m5ReRJQoAZxPh+jzA9ngoUwj/LzDo0fv4YTkLkovoxVVxCDkpydrxXRvrRCHhfGrE7kkddSMGI2u4JerdRBubJccHbOGJwa2UqGq3g=,iv:7IdYvgGaPucC9VKgL9tYWQvDCPj0E31QOAlOJFvBO2g=,tag:0T+08xbOQMDrbe66dT69KA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
