kind: Secret
ansible_user: ENC[AES256_GCM,data:LcQJQQ==,iv:8jnYL4dQft5m4ILiLZHvDfpeDBELAkJdiGiDo7+cC1Q=,tag:fij9L3BhAuCNaJ9GXYHToQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WSBix+VLvPPI6Q==,iv:ZetreFSPYrOVdV4ou90Rh+ExpwYrvLMg8gz1LWtPqIM=,tag:aCKrmiLoqabcMzey3B2hJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQVk5Nmw1dDcvZkVHQnAz
            RUtJNE9qZkZuc25Ud0JMUE52ZmpFU1U4OUhFCm9pNW4yRm44TGxRaU5BSUhUZVJO
            ZHFKUWlKWGdFWW1vTlhQeTVJMFU4N0UKLS0tIGpZZWt2UVR4N2dYOEFmVStIbktt
            MnBaYldyWW5VM2pNYlJNK0gzL0xlb0EKrPNW1BjKSdg3/dL+wGL4bHxE19UCaEmn
            WgPNmXS9tfZhBAo4bEPjoGre5fteldWZTs+sAoJkBCTTPUbVXZKAQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:37:58Z"
    mac: ENC[AES256_GCM,data:QZTzsCtKCQGfY5+iXnClRzoAlqUYczmpy9V6OSpI0gKH8IfbR7rxO+sCooGbW2TgZZRUDUohY95fm3TFPeO5VTgZqE3QbjQGXMAXktJvvtPmItSqrIiIotqjDBdD0Ieh38RRk+8rkye559TkgJsWykjogKU7T4HNCWpDVA0Sh0E=,iv:7OAtsDd+S4tTBxsErUXAiTY0eTxTDl35Zw7m7zZ0nqM=,tag:RE8ZzNUaL4xklL3mOm9Hqg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
