kind: Secret
ansible_user: ENC[AES256_GCM,data:5e7CTQ==,iv:FYsq54GzWTWMuwjkWZzMw874jedp4Ccpsc1CB+8vHxw=,tag:awTkd1Z3ZIpTGrStdFN5Ag==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:uwaPis4cnaih2Q==,iv:1YtKrZzJvVKlTCLfW9iZK8X9g5SmZ53aoi9aO2uzBek=,tag:wTvNp4J5jVNDrATRjcun7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDL2x1R2JRYThBSU5ZdnpX
            UDg4WnJZUy9Yck53T0wyeEJYMGRlRzFubno0CkpwY2l6UDdhU3NxbmRsWS9jcmxi
            RStHM2RXUjhiTFFkV284bldnM2l2WjAKLS0tIDVMNVhJcjNKVnU5cmRIbEE4VkhU
            MXVwR2VGK0NBOVpGTnRub0VuTkR2STQK0di1QkSMjgf0+srF08IEsZ+qwoz3gGnQ
            +SxRaWm1Ub6/Lq7Wni63VazYm0IbyGEaY68IVRXl19HpRM0DLksPAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:37:58Z"
    mac: ENC[AES256_GCM,data:4SBy9xHNp4TBti7JxOde3vHaDOwOnTd+W/nZdv28KscZMQDWZ1AR7rQhhDJ7KqIzcMP1sU6Pka0LcY4KGsfMHAn293LLZMo1cMdmYCpFXor2oVHZVwU2vxgdvn6iBPhorSKEBpXSB0JI3lPRuE1f0HPvLi3UGM4Zqu3WFK2iBvo=,iv:gaoA2qvDZ3w335f8NU+39TzO9GtPSrN6513jhpMi9OE=,tag:zMaccgvqkSx76+08K013zQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
