kind: Secret
ansible_user: ENC[AES256_GCM,data:6aOOOw==,iv:Ei/+G4MmCcQpCJPQ9xgOR449EW8cUbSpp8BBDCLTeQQ=,tag:1tc2EY0CoJsJwEeqw93nfQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5zhMfpIe+esxqQ==,iv:rPal1DArDG11KZnOdeMg4l/JrViPkGF7fFkbSlSAuO0=,tag:ZGvK/pIr+p1uJbAagunKYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRHF5bHYrdm1jUXRHb3Ay
            M3hKaVErYy9jYllCS1hacUpEOUUzRWVNZFVBCnA4aE51QXpzUTlQK1BlODBpT2I3
            WVBSZ2gzOWJMUG83bDNMdHc5MTd0Q1kKLS0tIHRTeThwTFpHdmRmdGJOK1AxdmIz
            d291ZTdwdVlLRU9RNjNOR2ZUVStSbWMKeWdScbhf5ae56MQxgfGdbUFWxBhq+Dps
            ayETk0y5y42FGNdO3Gh00wVEJC831quvvk76JJjDmc/zSXogphT1zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T22:35:46Z"
    mac: ENC[AES256_GCM,data:k54SWTANPSwvPCeIfNcJll9hcKbYzay+wyFvkcUYLC3s5OcNb4Ky78oRbE/2aNBfDWmHmzZjDeBOMlte9n3l08FUCWrwQGA/ihLPZXkHAHnxS7frFfQp+v/fC3uZIHpfLqMSfWPLB5h67tUl7fjfVgCPgOrEMsbeC5v3LUYbsAA=,iv:15sVYmPde/Tx6slnmgGtz8YQWLtsLKh7G5J7NbMZHhU=,tag:GlA+S7tuXmV2cac+gpgY+w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
