kind: Secret
ansible_user: ENC[AES256_GCM,data:hyxwYA==,iv:ppjoC1Ah81s9bGjJApYjRwNpKh5+o1qsNsjYCxtfAsU=,tag:Yl1e1Fj3IWBmhV3jT1fXyA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rWcf3sselhdrPA==,iv:E1CVH80iWI23XPkwAyQthEFBOvMirCBEyIJnj+nQ9as=,tag:shC+B1awWeq2LzLqdFynOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYi9pVTA0ZmRRN3RUOWR3
            Sk1nblFBZWZuNHZBT3k1U3JObDQvWktWMkZjClhJZWc1MTJ5ektoZVNYK1p1ZThX
            L1g4blZONGNWclY1QlFGbC9oM2N3Y0UKLS0tIFdoN0V6SVFaalo0U3hseTNnU1V6
            V0xOa2RpSlBnK09MMzR1NUhxb1JXeUEK3ATHJ9W+IA+qiBpDcqJV1pjVhH+6D04d
            0My/HLE05oNUrita65BvI7bzb93jSlzeJLz8wWlhM6liJGN6AL509A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T23:25:34Z"
    mac: ENC[AES256_GCM,data:URFPv0j8S/4/2YCQp+iXaCH+hO5dmrrEWMPzfEyUFEbQystXocbzMv16NU6r7IIc8cstpjgAjjW2Td/LrzSzUEk13+RLr+nmGZK0IGF0mmZAHWAyFf7VsyrhaPU1queCWWV9U9xN+aER78ljFv4E5ykhr+pwRzSgobcxRFz3eBQ=,iv:b5tWVljn+CUGLDwRHWQVokOmuVtLMzU58DEYB40Gk6c=,tag:10Ektsqiv7nrI/mfYWoIKg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
