kind: Secret
ansible_user: ENC[AES256_GCM,data:/1x2/Q==,iv:vHCllAhZHlUTsQZ7tGmiaPAhkA1gm9BYK3edWy8zr6I=,tag:Lm4kIB3kHnaKHZUhCjBRTg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jli6nLZ1zex5LA==,iv:uqsm2qbAJeYOrsML5HwP9RJ4xruArjwi7hsMhLyZzvY=,tag:ocgakR3Sbg/Kliwr4EHoTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMHI0VXpEcGhpKzRVOUYw
            dmJSYXRvNzZDQ1hudGcwV1JaN0ROTjNYa0dJClU3RmJTbGRnVjdoMHNpUWVxUVZi
            RGlGQmdLeU9uYlZOR0tVUHpoa3U4QU0KLS0tIHNORFBwUW51YllJVWZKQTZWN25R
            ckhaeVFpZ0hnY2Erdjh4blRCUlF3RmcKn05mvlF9nDOMy+hMO3NcfR76cqeHuV6W
            QZRtHRxvREpkP9zEeVbzHymOvqqHg64/kGf4ecZ21rZpyOBbmyGUvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:51:24Z"
    mac: ENC[AES256_GCM,data:UVBjAuIFXEbjLGRSALJRAWU3fVariuqnsCqvyHyfGAm4nepCJkBPVZRzq+KJ4d952BhU8Ao0tAPUKraL6YI4m2OpVtP38rqIK+tVMe5UVNimS8mhnaQUcN5C4WkJcZ06oVfi6eUA0KjqZVifkDdvsXYqs8J42KRnSWmVnLwb/9E=,iv:/6+eT6S9qMHpZnUgCBrCc5ulDdg6WOD+Se85b+cdmw4=,tag:xE6fhhNtSIifaQeBh95ilg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
