kind: Secret
ansible_user: ENC[AES256_GCM,data:q2Twig==,iv:Y7VtKQ6c5t6MvsxTG4AaVsRrkzvQHwJCH0EqBk4KnYc=,tag:rAvyUrxCewVzM9ZkQstW7A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:C/HM9OikQZkhLQ==,iv:gyLHt0uyfmzuo9WFfrJOQJ3j7vpbIyEUewVaL50VMb0=,tag:jW6f6jC3UIhedpsTKOs68Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubXEwM2RvT01TWE5PK2My
            a014S1J1SWw3RG5La2E2L1FnanBvVTdIeHdNCnlzTGp0VkMyMWJucVhRZ3ByRzJq
            a0U1OS8wa09qR1hqck1MQ1VrdldWVlUKLS0tIEdscUl3SDc4a1dlNGV6UDBRRGtY
            Y2d0RXVBTVJOWEIyZU5Yc0lIY1JoeFUKZO5CVoSh6mR6g/8IDRTOojCwJefRldZd
            DpBj3O5QX2caJSCPiynzxoTINLVs2r71LyNUaMrsFlfC94YyseVyig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:44:28Z"
    mac: ENC[AES256_GCM,data:3xEtwVy8AiKHhTUUGL1vdVd5nRwv2lTEADOB2l3GRNeGgUib0qyBGTPk8Ft4F3ll4u75wwKRzxaZOZWqN+dRsAxB6bS/SK1wSaZDEbh52Tf4hwtfy+8d7UtfeXLNjTuFIIs4qm8gL89waK1BRmC8eLZyFXGwoM6BXcVNREdS97c=,iv:QBm6lWMsXrY69krmQgh6EW8ek41dqfLSk/wgEtVs/zI=,tag:KFxK8QP3wNDV7l3VbOHI/g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
