kind: Secret
ansible_user: ENC[AES256_GCM,data:9crVCQ==,iv:oI/mmAGT9gptR2UiWNy5UBdYYsQos09taFW2UqSx/EM=,tag:LHGR7F5KS3QGG49olXIAbQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jBK3UOwu9KUsbQ==,iv:ZhBsabso075KRDJfG7vKbNF8y0xceH2wq7bCmRdiLJk=,tag:klkAtmtl+OxZy2stRh/WWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QVJDZzJGKy94ZG50d29O
            T1ZqN3dhTmFNUmVZcElCS1N2RTducy8rWWdjClA1aXpSc0JVSFp1NzYrd2NPUmpv
            b0FaYW1aMHVMRytKZEoxNC9qUTNYcG8KLS0tIDZSQ2c1SEFZK3hubHFXdzBrYXNC
            eS9DdkcyK3JJMU4rQ201WllIellRRlEKk208WL+gZ4T0XXuLPaKHD04ZREjk467t
            5AAzvCJoWiDCHHMdEf08loswABlBkbBzVVH1HxAarF20RNdXWGUW1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:37:58Z"
    mac: ENC[AES256_GCM,data:ntR4tUuYmcZhNTz8v7kWUCVhtEDmYeJvctTCSH1w9o4bwGKLWDeVTuTnCQPWny9IG7rH8/uKxzERQesk0AvjF/haeCJk8/58V+YUpoALNv7MOfKdVxrhKLwotHUEpCM9Niq6xPYUpnAM/a+bhvCTP7m4AveJ0vovCIvPOw3tIzw=,iv:Wu4KXE0QCesPAFhwH62Guo2xzD86YB2+IXdCon0Di5s=,tag:q2Q/hWccMSYc/JM+431Hew==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
