kind: Secret
ansible_user: ENC[AES256_GCM,data:xkup3w==,iv:YTWAM7SfgABdxBxU7PX1JMgqJ2u+59xvDuwp2FHkQ6w=,tag:3Ax3zmWTGfPAnLwzq9oMaQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:v432PV9Qv4v2fg==,iv:uYj2Ms3mKwcW3C5J5ihRYxqld33Nhg7JU5Mmp6YkWek=,tag:MwAaeSXfLUuM752HGpsK+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MW9ZUm9wdUFDQkdWSFd2
            TlBVUWQ2UzkwLzVvdk91YzNIYTgyOHk5TmlzCnUwUU1qMEJBVHpiYmJrYVJLUURJ
            S1NMeUdtWSswM0trNlZzMmF0cGJQSVUKLS0tIGJrbWF6dk12UThFNmcxUVdOajR6
            NnF2V1g4Ympac3lLQWMyYjdOaW4zeWMK3/9kbC8mFjF1CYKw05UICPzViBBqKo6l
            SIxi7Dw5X8FaTWtQ39fo+Zd3ljnYh8LVrWsrhTEtjq4vVrknr7VO/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T17:28:30Z"
    mac: ENC[AES256_GCM,data:bOGev0RI+L6pvEF20HCh5RLplQU0WQHfoWui68kPoFp/2IkZhfWHNTmi/XDbFWXKytTGyrLqlM0RW+DcTyNtSA5S0hKkhHm3+pcpBct6CDKMG/z8hSOwXooY8td10NdsiHYBwqdFPeyPVi/o76w9KL+AG0Zi0NPZVTi8FE0HhzE=,iv:qSLhB24V38qbhVjasiDsEcv+nhq9l/ZfHHjgPUnMZlE=,tag:/ygMyauRDuAZc5dckbpWPw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
