kind: Secret
ansible_user: ENC[AES256_GCM,data:oOysYg==,iv:4yGQtR+LudS8KpAdq0/nPKZoAp1Ep+V6SRUPEovA97A=,tag:Fme9O6tYVHyLrNeWyuAzTQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zzXRwvsj+VlNhQ==,iv:ZKGZRi7j9BIEaB24yGf/K4JTR9J18oV/oulfmMwB9l8=,tag:SK72KLYPjr13l9z/QFwU3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTll1eXQxVWVNem1OUzU5
            OWFBU21HRUNMcEFld0s4aGlBN1lzUXdoQ1djCnhkRk5HZ0lzZ0lxMkF1dVRRYmIy
            MlA5NDVSM3A5SmpkQTV1OXBEdGZ4ZDQKLS0tIG1uZVUrTWFPSjZ6VU1FMHdOTlBH
            dkJTbUJDWHRUNVEwcXU1ci82SlBDaVkKLL7S0OaesQCE23gOIWlUVVbnugzgauhj
            nJ+w3NCf44lVmpnenaWsfsloef/d6Je1k3DIsM1vF9831o7Wh0zgPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T15:03:40Z"
    mac: ENC[AES256_GCM,data:6v1gkRA4FHonCwICZyTZEjbrtR3rxTii9v/LVlCUo/SgD8jyyK/oWJOk7uez19pE41rLLmsdZ+oDQyIaXFgtnXd4C7j4ePisNwnzT7P2hBt0JT2zhgExsEelFsDF23NIpHWNOYsyplFoIM4IZNLsH6TNvVtT4klKvT4zIFHvUZM=,iv:USlVlsJ2sUzoGARRAKyFSL8aQQ1+tpsZQo+OikimHM4=,tag:Qgc+pF4r6nfrB2hR9M1puA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
