kind: Secret
ansible_user: ENC[AES256_GCM,data:46CSzg==,iv:RGho2ROtpvMfWXUx4OMT3/FDn0awKVdgInbWui6p9dk=,tag:GBi/Qr30RoKvfyA3GW8RXA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:zGTriM3qsX5IqQ==,iv:/733ZPxSLiSHFV1XNi+TxhnqwDtGlCJdRPyYrd87BgM=,tag:mvyIo9ab8zc+VXwOVM2YVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRy9HekdodTZKZnJZb3BN
            QmhPbHBVcEdWSmR3eGdOUGNaZmdBSDdYZnpFCklCRzJiWllLdmlvaEEzdEpFMW9N
            STZCdEZYSjdCUm1KbnpIblBLN1ZyVFkKLS0tIDlaV0RRUGJqVFY2c083U0FYb2Rs
            bnAxd2txNXhhU0tFVVNJZWFZdm0xMG8KE/+aciquogr8ijy7qsTt6N8gLeaUQ/Qk
            cwEsKy2F3Zy9wgT1qFn0AOqXfesuf1xsBB+nGCTVFfzMh+899+la2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:46:34Z"
    mac: ENC[AES256_GCM,data:dtv0gIt5QE0/EE8RXqxeTmSlc2JK0l0fHeImnh24kY2L6X48SL3q0lHPafs95LkJIL3cfm1Fm3W42WKoGKgmx3VXF09EE0nJLZoO84HpcxbFSevxNs0sh20kZxgz5LXZrqfMVB2e+4kANbl0rA05R6Fep9Am7nH+Rp/3sS7Kc3o=,iv:2W7+BL6ymcVrt3eSJyWRkuOEI5Ts+tiznFUFRS1mLoU=,tag:+2NnSF1QKmOTSUAmBtmwlA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
