kind: Secret
ansible_user: ENC[AES256_GCM,data:cITxUA==,iv:OWJz+9SNPZv9XeRWdv5P6FHYJm2whvQlE9UWU6+JUIU=,tag:H3RSIV7kJMzieGo5O5IrLA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:bvlprI1dgtjQXA==,iv:QxWBJJ0ofTs+0hFIjAP0YWuidEorDnHLP6paPUheWro=,tag:6TIplnTmTIIbcFKoxdYzgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdFI4WC9UcForUG1BMWRV
            b2FxQVhteDV4dkNQTFd2bm5hM245c3R6VWx3Ck1QVzZnQWJEWTcwWVlpU05tMHIz
            bGIwdVdvUkhTNUwwd1FOL3hQdjJhcFUKLS0tIFl1d3NjczlMaTdNMkkzZFJOV3BW
            Y3ZWcWczT0lSbWI1WHR4SEd3YXd2QVkKct1gpcSFZJbecgpUGoUhnTJDpfn6J2qm
            3mqJnZF7muWZFotOXYrOQ5r6sGCMUeauVVbK8Ivz6/CtQ1gU1FkFGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:51:24Z"
    mac: ENC[AES256_GCM,data:V8uWw0KCqnLLRY9tSvvtvle8a7N/1ZyyyNgczDVXxnQxLHN1La3ixJ8YfiGw4zKum/PcO+kvBn7n9XZs42bnqu4rBjtmL3SIk5oZRmSt++M1VIjxX+FBB4TQQBDi2mzytOwF86BeNQ0WItqyeLWoJIHN3DwlfKS/0k6R/g3gfW8=,iv:VV/EpIYgdAPbxxgQJn9WktmxB06bxiFIDldvO4sWhCs=,tag:0LnVxqdTc6W1ZcjMcpQtLg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
