kind: Secret
ansible_user: ENC[AES256_GCM,data:FBwIbA==,iv:gxQ/8yQu7scCwQ+Qxraeh9zXoMhZc9xDFLwuDuqFFTE=,tag:IUhPGsnhV4bAipykQKUBew==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:y4l7Yl5xEaW10g==,iv:anWWIucF0gcnlbzx3KiGpTiKSVH/4j6PgXrsAjQTzfQ=,tag:HJCENudPcyPbUGf52mKV2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZGFkSnNlcG9kZEtLQVBt
            YldrSFF0MGd5Wm1hcDMyVTdlSzhUS2V3c0FJClcrQTUxNGFpdHJhaEFabDhwSjFQ
            MWZubmV5NnI2KzVxRDJreWRwdUdXSmMKLS0tIFJGVHNEWllZaXhkT3JpNGRHYVh4
            ckljVUsraFdWamRMb1hLVFdkaG13TkkK+UwvDFeYOLsR9CxV5GQeIRj+Ik4CTNTd
            RbEyWjwew/BrshADw/+8Sn4eXKKfdMxG4Z/5+WfERwpfIbdwCBISXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:46:34Z"
    mac: ENC[AES256_GCM,data:BSQ6aG6ZQVTLnMBlbY0Km1EZqDiGkggdHpguRmZGJR6uCbG743p16y0hcKXP5pbQdKpZ93ErZ3rboGkBSy8ob7S40gImq7hx9G03/BBA3EohaLwfG9NsiGOK5aRHifdwVVquhqP5jJQT5ClcaOlk/QIL2JTfY9+azDsJSgSTMQE=,iv:yi2nsZ1kUHcNvtFmm9cfbIeA/T2yz7DzuDc6D7EhkIY=,tag:D2Hbuj5p0EW6ggFQTw7f3w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
