kind: Secret
ansible_user: ENC[AES256_GCM,data:63k3tQ==,iv:hGXHj9OB6rNrapnzZu9vrgsYULF7a6kMTuj1N1ioSnM=,tag:iiVwzY2C63A/9fUCkXsl1g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:RtHkD0WXW59J9A==,iv:8XGvh1VwuzdSXrKyj0ryjpVgpq7qtvU7wOmTaoMUfEo=,tag:chgbgdroqfSByN+6n2atrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTV2tDL1pmVERFL29KYVVR
            Nm1VSDFYNlNkK0Y0NUI2WWFUa3E4ZkpvZmh3CmxkSXVuNEhIVW1HY1NwbXFqZWxU
            cHVNY2s4NjB3dE5naStzdDRRQmR5TU0KLS0tIFdINnRMQzMrT1lTMHREakg5ZzlF
            b2ZJVWhwSkMyRXoyUFNDN2pUVEtkaG8KWz6Umcx67ccOf0GjWwoqDyceqrwKxYke
            1NJXprpTmDUXWc4QSiv5C5vvikkWfLb0P8bqe2oyhDXFgL28u0/32A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-12T22:07:58Z"
    mac: ENC[AES256_GCM,data:rpVx6nGZnZACqM1HnV8kTdQrYgcYTRX+4bxTNy6+WFx8Vm4kT3Ajk4ZycHYRQg8jgAXw9hto5Q2hLNB0tkZLvRKcSs9+CZXqRx7+Qr+GQjhX6E0aqRVdiYsZi62r8imXNDagFiJDbpnTgJoItUQLXu35amS7s5Nj2LVTQk/ZFUg=,iv:B5V8PGJsleIyG/xynaslziP0pGlz9xwT7LI1hBnuon8=,tag:TXLf+HVfMSlYVk+e50/myw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
