kind: Secret
ansible_user: ENC[AES256_GCM,data:7cH7kg==,iv:cB3/goH5y/GxO7N5p34H5o17O5gocZii1rLhGLME77M=,tag:Lm4KLYvkYzqVoi1ndR5P3A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:JqXg6GXnKwTBoQ==,iv:8hm8ME7LSlvN9e8kGZXJm1b9ddwFq0+q98doslB8obA=,tag:CyMqipuUr3qCoxzKHDAOdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY1UySGNra0J1clpSOW5t
            RzA5VnpINTg4ZWsyVWR0dUFMckZSY2M0Z2lrCjErb3o1Tmd3blJqRWhUODZYRG85
            RjB4dFBqb2R3VnpCUXROZnN4U2dDZ28KLS0tIDQ2ell6SHlHVXJGUlRMMFdQQ1RT
            bVlYRlZrY1lHSXJLK3M1UU9uaHd6ZkEKqILvw3G4WIaOhO0PiK1kwDg/5sL9J1En
            oMmaQ7Zfpc/vWyFAqPWEew1nBUSO3byrY6JCn8er0wfm73aooam2TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-13T00:42:53Z"
    mac: ENC[AES256_GCM,data:vNco1tRbCiJPanp/Ejrjp1jzXmhvXSabv0UFctw1pHoq+8XmdgDDeICj7df6O31KvHX4cAEm2c51NYPwEAYO05mz7L5RLVp4F0SRUwe+RoE5ESIAv1u2d9Uzkg0Ebg2HhaEHUEWF7AhESp3PIh1BrOJ+YTLxcyEY/lsZtjVSqkk=,iv:rOh/6VRMBLGG5nrSlfuFkqIQqMJtFNlccWaPlIXe6yc=,tag:lJQXJJxVFREQPbCsCo3YEA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
