kind: Secret
ansible_user: ENC[AES256_GCM,data:xzhg2Q==,iv:FyLhLxWeMhYU99KjEYnuXSjqQWfJufapkKTig65UJ/M=,tag:7wVlAOQPJRkz6x9YZyrQxw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:uYU0K+b5APZwRQ==,iv:jG2aaIU2NSoMN7r/gcCB0w0mufcBODlRQeWbuWzQXi0=,tag:w9uuMA3KBjp7yMzl9lMxxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMXQyeWNkT1RPWnlDdmtT
            ODdwMWtWV3ZhV0dtcTMxSzNVVGFTQnRLeTNrCnQ3N3RuYnVoKzJDQlFDb3BKRFRQ
            TEJES3pxSk5kT1RLZmZveHovN1o3TkEKLS0tIGpFUnZBS05vU09MaWpxekQxK3R6
            VDFCaDBqN0lsMndQaUMyWkhRcmYvenMKUjszmyn7JTmYykTuSMkI7F6lKGIJaxYz
            UqGsC/Dx39/xH/PWEqAXf/ZYWI9ezDOnYI3SO1KenU6ZlNB0/QNEbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:46:34Z"
    mac: ENC[AES256_GCM,data:puiEE9+T2Q+C6mjdqYnvvuZc1ENsFKYVTXQmgGuSHuVEe7cpcLwqvqoYjMN2mia8hwfsTeO9op6tK1aA+J4d1Nrnomsuin1ODGY4LrJNbVEWtf6NfdFnUDaMdmv+h//csRMaNFxGcZfbtyv+p0y07L1szxKTN+kq6fkhjs6ylVw=,iv:PVfl3ooUR9J2fRMnVFbxCFqnwQk4lpiVuewq83AmHBk=,tag:p0LMSDMuwxaG2BnAayWCdw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
