kind: Secret
ansible_user: ENC[AES256_GCM,data:STbFVQ==,iv:/74RaDntd63WVVeyOa6Jm5RQ3kKfWKVFS+8wGJIo5qM=,tag:kI1IsYIuDVwTNfgFNrIoAQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QAtF27lO5QOitA==,iv:dg87K9nzTyUDXCvPPCXsTDBm1B+VFeaoy5r/o1r9qGI=,tag:uAQrrsejM/kGzGn8M/d9qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT3FDYlNxSEZxazhrcXRO
            ZCt3VlRHVE5heTRYUUFWS0wvSDZTeWlUdm1NCkxuMHpZakYreGJWWkdSZGEwMnIr
            SXpWR2V2Qll6RkxnR0NJMVlaZkt2QWcKLS0tIExMck11Q0NxV3Z4elQzRktNck4v
            cEFES3JQcDh5bEJLN0h3dnZ0My8zRXMKgujlbs/W/v5qqnGVNZW9yyT5DlgaMpuk
            a0xELV/TLWbN6ChQjwsX+N2OQ/5eDiGMTjH4afqF2543exobVqnaag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T22:58:21Z"
    mac: ENC[AES256_GCM,data:xM6NiiCNx6+IbK7j7WObdFtzMKW9MbDQy0pkMxyKPqVynmwi7HBipaCs6Di0Vp9EjG6SpFVd4EEH8t1VlQzEMWxPe6mOrEol7NAkCtA7GdVDU59GViMAardfFmJEvkcFQYWURkK3bAqwy0WhQwoPcv55NjM0q6sD62sFyDqAYaM=,iv:hxk1pZX945t1S65fPbTbBkDFjACBUd9BDHK/odaYM64=,tag:AJfE1KG78aT5zLGhqVuQ+Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
