kind: Secret
ansible_user: ENC[AES256_GCM,data:PhA5xg==,iv:0qWvLKuwvP3XGFOSF1mqCzRHlSZCqRLmlm3Ietqmq1M=,tag:s0r1JtY02p30bWEb4Ezwwg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:RA9nTafYw4U9/w==,iv:X6d7NPX+p4FWvdZxkWV/h/HPXJxXlNorTnERf1zOJpI=,tag:44YKSDyMBKHjpTBeV/a1KA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbkRrY1F5SG1CMlNKL0Yx
            ZnpOVjQwVXNBWEdRa0JKTTgyNWNwV0tFU1FrCm0vaDV3bU9ORzZjMU8vcWpqVFdu
            U2F1eVp4ZUdUY3lId1ZRLzc4WFkrWDgKLS0tIHJFU29xMUM2T0orOWVVL1d1bkMy
            bXhyRUtFM2l4U0xXTUNSN0lrVk4vemcKB+YVre6QrsjaATr0h8ukaAPc6v6wBhet
            q6gaei+eb25vuXyrOrrCs3oMGBI+JeL+VNZFAlTIu5TE2lzVvn0jnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-09T18:37:18Z"
    mac: ENC[AES256_GCM,data:V5WAGwhIZ+qcLbq0euk4FVa8m+tIjkYczyIZlOC2kvGwrCWmQOdzwBsLXvQ5mDm3xaInM7z5hmQAG/UgRMF1HGL4j46GCTlnbEd2q1+vGUPepb9eizIaKP8WtiOTSkT9YUNT3prmTAMwhSjgKkegiERp6+2Jvt8LCMggMrzMKRs=,iv:3a4MDkD3C6gKC25TqQuY7e28fiK5fAry/5UMfZn1cbI=,tag:Vz1cyFK+275lBeT2JehFdA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
