kind: Secret
ansible_user: ENC[AES256_GCM,data:7B1X+w==,iv:AnGvIWcLNzHEv4KOceXQuBhX/yJf2G0XsHBK3zmdwtg=,tag:gejyOAn7KjqXNoo7JoBHRQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DFDYQlFthafF4w==,iv:vnU9D8m0Eo6kVZg35iA8ozlxG/Nlsyi0Qajpi4V/0Dk=,tag:EKuMtx6zG8GSWZsakNeuxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOFZHdFF5Ny9LWGxnR21z
            dFBlZE1IZFNJY3M4ZTRicHVCUjJPZkl0dVhJCm1CQXYwOWlkRGQwWGZacjJuR2xY
            UzhZWFBzTUI2Q3I0V2poVjFET3hnM2sKLS0tIHhyZG9JN0lyRm9BTEJlbHR3RGVv
            c0VwMVBtTzV5WGRQcGNYRHVVTGJrRVEKztsl9YC/dHCVoBZdk8HQMovf3WZiBnh4
            LJR+ghCkUwsUHnN5TramsXt5J8cS0rshOqeiMjp9R1frxeyd6SyIjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T15:03:40Z"
    mac: ENC[AES256_GCM,data:CEOioCohMly0S1knaH2kk4WWDvmqtqpVMUHVyH2js4mAHC3zaOOrnOUNhdmIm1ulz+Nz14aWQ2q2o9qX4jc5gwstCV3bp9Yw2i2XOjx9HnBkZ6PJIdUADgEl+gTK1icRtxLTlkK3jOrY5Suy1IGb8aqXTK5F6xHz0Rr6QCnJYfo=,iv:y+BO/G0DRVpOarELVMAzy2VsG/9oUgNNgNZ7iZN4sw0=,tag:CbFPrGmXuzEwMo6R1M4tKw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
