kind: Secret
ansible_user: ENC[AES256_GCM,data:G6TC8A==,iv:Sl5zS91vQ7Djvif4jLjUmf5dPdzKmQyYUMsXnhNmVFU=,tag:Dv33s8EdbMd9baNU3dr0Eg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:t3GDNhRMPuFJEw==,iv:oI5fpZ+SEuDTB1p6+HqoF7KKNa1ThVemshtZk+6wpbA=,tag:3SgDYkThENJ0MZ4jelgb6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU1M0VWs2Ymd2OVFoMzJa
            VGZkZnliZHpGRW54Sk5nRFFhRFpZbURSQkcwClhuWVVVc0w5RjZHS1F2aGVaMTEw
            Y0lPOWhlQkp3elZFaUUwT01YeHhjQlEKLS0tIDk3djBpQ2VTVE9TTis1RVhDS05Y
            anI4RENORnFQZEFGU2RzRkdsTkdpL1UKhvUXA2QPrvr1ruCBnypXx1Wj7q+wYpwq
            ilDR+Z981L1qknnP3MHmHtnAOxOGG1OGOqcAnSEgnN3ZQ/9q/GGGLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-10T22:32:43Z"
    mac: ENC[AES256_GCM,data:HXHyDkUVuWkcGwGQcFmXFP6g3KOk5EhanqZh/VHO70UYYJMH1+3Dp7jyw+wus6H93Ykz9hS6qDQX0HrXzAX7wd2XR62s6/jcHQjCOAhAvhFLgRHqiJl7cDDFvut2xEJSHWwREP2Sn9T3Ex2yG1vdBC8/wCIVGU70dyUL098wHGU=,iv:f0HTt+xh3aPj4sqH0U2ilSk2cUctO44cftVLbGVzaEU=,tag:H4rq8R4JzTV4TOwQc3lb7Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
