kind: Secret
ansible_user: ENC[AES256_GCM,data:Jsy3Ug==,iv:F1bEtqXKyh9Mhn49wbfuZ6zLpBxM8RjLcciuUjzcR8A=,tag:aNwKaS5YH7rcD9kyYG6eVg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:hP1fKR+46rzRKA==,iv:CMOiFXMJRDtBi3Q2CYwQHELut7hUGJRgXxgFfziym1U=,tag:PwwVZQtdhbXD9vfGVJ/oxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbWlrMTdib096ZXJNOWZ4
            Q1VIbW5Ja0ZwcHlKNWpOM1JxZFBPbjBBalhZClBwQS96WnB6RExWbmJpQU9rSGVV
            SmtteENzbTd0ODdqYjd1eDJaL2N6VXcKLS0tIGYwd0tGQ0o5OU02VWM4MkVCaHJq
            YmJIU042bzNNOCs3YVRkVHhkODZkZmcKZl1Y3VcX61SjZs4O8hR97vE3FtC8Cbks
            IFS3TxmbCCkyqs3nua9DUfd2iLMh/9UD0TJnZtWCcKLa2Pgo8/+I0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-25T14:51:02Z"
    mac: ENC[AES256_GCM,data:5RYbxLHKnQDc4ZV2C7g8q8aOLeoE5kscpWYpMtvU/ysn9EN7WNv6KMG7rDFggL8KGhR2qgClSwNyd+/uPzzsKPXbxVr3CSEynI1iGvkmjgRO+wQGPtcqbptzE9y+c3M3MyNTNreVHX547YBMMGXwlg/qqaYuTZX0uvV1eCo7myo=,iv:zCZT49n6VYI/Zz3HHLEcVhbOSKRyCzg3Ols1aWgMg3k=,tag:uMJaPYzz89wXUdn9ezhdQg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
