kind: Secret
ansible_user: ENC[AES256_GCM,data:L9tB9w==,iv:xM55tcb4rV3+9L4YQbvA1fBIZJyVSMJ6kXZN3MD3J6k=,tag:Gwd73E9UKNsVVCpOpvbmBA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:/dpNHf1b8TdTrQ==,iv:iWLijtLZKHeqQXJyoa/n8+It4BkzLZFozWvX+uAvZ38=,tag:MGcPoVSQ1HZOkC9nbksaMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSlJFd29uYm5aaWFocDVP
            ZWcwTHZvVVBpcHdTUlhVR05QSXNyYldROFFvCjlwSHIvZ3F4M3krSVpvNXZKSVZk
            TXhXREVrWUtjTHluZVFjdEJCYTdEN3MKLS0tIGhCditYSGF5ZWx3aXdqQW9ONWs0
            K2kxNkl0cGJCYVhxSmlTbG53eDNqbEkKPdseUvX1w6NSx/AwenccIXDIO/LWc/iG
            kG65FlBJdn4F/nJ9noaT30oyEq0Ud3NatvsY4rkSfAXV/auFgEKdbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:46:34Z"
    mac: ENC[AES256_GCM,data:LrI98FxXqTvd/hdGmslKlas9muFWR+zAa8JkH+hcTW4zUj+CFrM08ohDj+Iy3JYXB5m7VqLHqHXXfSC7Cc+QL23rwX++Da1826SM1/cvgBizq4qUEpAWcmRoAMRB6mpw2Bt3Kcy8q+HOXnUqUQJaf4l5mvXGq0GALUlEVCs4sGU=,iv:iEr9jEIlTEbZy92huUkbfnNI92D4bJPqiQBBzCKpd50=,tag:1VEkhdLiFRyxIpUHTPWoVg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
