kind: Secret
ansible_user: ENC[AES256_GCM,data:+sgVBw==,iv:Kk2pV7ehr8k8PIMpbsyDKOQmzdJJR4TjBktHN0loAIY=,tag:zH+jRRb7x3ZpTlceA0Zq1g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:flBnIpOJgdtviA==,iv:F4ZLj4F2fIEInn7lHI1n4T6x4dm597QT65V+ld0THe4=,tag:D3pRZlHO7+SImN7WB1kF4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQU4yTUkzSll5d3ExanpJ
            OHA2dzQwemhLWDRhU0U1OUhQMnAwaytJaVZFCjhBajdXcW4zZnN1dGNPQUhtcWZH
            Tlh3VG16NGt1Rm01MnNaSUx1em5qYVkKLS0tIGY4REptNlNORXBUUmsvYXh1MVFk
            dC9naXp1Zy82TkJrdmNQTUdORnYzMEkKVwoGJs4qQAg6dihrKZvGo1dFDMn0Njt9
            usbKb0eShLcBLNfIea1dxlQpvpYj6ZZeb5li5W5BvMtHEzHsBuE0yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T16:23:56Z"
    mac: ENC[AES256_GCM,data:HOx6Rjma/aUGQTx71ovtwJh1+9DPh8n9WI3yFJYwOwQP30cRaoVVtfIqti53yWn0dsQuqghQj/r0NNjkjQX/t/VelTbBwhtmV7gxKi6/9N4lUWRPkdmU0k+A+T9McQc15xNGtj0ADOdEn97AzcEmIhbxVrstnqfPmXJVu6JHkAs=,iv:oKTg1rV5vwjqAkH6HutwC4QShtzI7fCYpK336fUVzO4=,tag:R+t9H3nTpJYLLyCC6iMdrQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
