kind: Secret
ansible_user: ENC[AES256_GCM,data:YtpcxA==,iv:8nChD+CR3VqblkUG4xWgcW0wwmOryScejxShVSMw/x4=,tag:EH+4m6qj/Fe9KKDflf308Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:6IM/lqC/AVU2Bw==,iv:WyPTzsPlwS5jhDWa878npNu7zPrkwJLNuf2Rc4oI21g=,tag:j9g7YeYJ3Epqu5RM0HuS4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR1kzMU1ha0kycy85dVFr
            RW9YamdESEVReG5YM0JrUWg5MUZBaDhiZUFjCk9DRlZ1OGNKS05Gd1FId0NPT2Na
            VnNtMEcxZWpqSldENklraWNQdzNsRmsKLS0tIFk1d1Z6TTFaMVV5NE9EK3dVU1pR
            b0RWTnlvNDRJTW5NSUtJTWRvMjRpTmsKEiIawxP3idtnVhvDStv9ZSPcMs+bvDCu
            RpAs+zwC157Ew7ble2W2yzmTvg/JCImwz0b+CHwNW3zb33nMybt5cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:46:34Z"
    mac: ENC[AES256_GCM,data:Dob8YpS+l7iw841F+SXgHZpT+AZiavTKxp9YecmmL87daWPRYEd+S2j50FcIiwypFcy5JBXlJwp1jB7agrt7Htp2448YH+MFX+q7GghsMZ2Q0V+FBG13f+mvcpT9aXvkiyzK0iduo85AGh3m2XaOknXXmNfopZNINd8qsRMfl5I=,iv:epGxjVfn3ZqgSmLDbTaUs1YdNv6m4U7R0rhPKRDf6os=,tag:FeD60GykPs40aabuzTF//w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
