kind: Secret
ansible_user: ENC[AES256_GCM,data:uefCRA==,iv:QQDcs2DeRPNrXY4vbgV9JLfTOVYjg7/pKodeoDPw6bA=,tag:1nnaIwsmf60VdOGMMufEXA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:foqFiZ9bX4z/cw==,iv:LLlqo9JkZJOSqnSWB4aCccMHMlAH4wjQb1A2BUiaW1I=,tag:YGOoONzUBTJywdlfVdF9cA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVVpINGhFYWdSWlAzdnhT
            dUdoNzdCTjVBdlh5WU1RSEJGMUV5ZVVoNEZVCjVONjJIT1dkbzRmSGE5NmRaTVE0
            MEZjMUpFcUlvQ2xkZEJjT0FnWWFpRzAKLS0tIFE0VDIxSjRZaUhQMXYzU0JONVB0
            d1U0MG54ZWl3dDFHZXl3bkl0ZytHSmMK7PFV/t6dv8jeiydEYr2fv6dAomZxhLZC
            sED/fRynBfcd4n092+R51i/uvbyZMywqRUKlokJxgA9lBdVhnW0lxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:37:58Z"
    mac: ENC[AES256_GCM,data:8GNzN+n0mKn2mZvZBwou/vFapEu3v4ZCTy8TgN06ezOXJOtvorOlB6tbIHBoba1fK8ML0KT4oyk9/rLKo55n4wYrbd6g7n3WSVjweXQa8etjnPA7FXIYhEGLi+X4EZ0LGscXYy1kY3Lo/yhXvT9oFfTnl+i5ZAKxl71TVk/1MUc=,iv:GGEENMaKr3M+i+GuHKeWkSXYQtzNtQNSWmHX/TUxVsc=,tag:/x234wTrmoAeNhYYc3/K7w==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
