kind: Secret
ansible_user: ENC[AES256_GCM,data:4SQ4SQ==,iv:AIXEvZYMSAncGwVb/Bpvg+/suxr8BsvwUGD3HXeLbbI=,tag:awCxBY46JNq7KRWgXM+s1Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8nDgvE41iOFNNA==,iv:VQNNQU9DIn5SSDIYmCNqxe/jTwORqzHTWJEs6uS5KIc=,tag:q1dV5hRMH/966ikVzsIZXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZlBmTDVkY3poc1BkV2t2
            Y01CNzBBWTh1YjZnMFhVdENxOW9wVXFBOUJJCkxDcEk4K0VFQUNhMXRWWFVKWUVZ
            VDh5YXRxVXRGWGRtdnF3SExCMTB5MWcKLS0tIEtCay9XTkVEQkI2clk1TjZiZ2Nv
            dnk5RjVZSWg0L0lROW9pQm9yaDZKZTQKAPqAtpSZq/aNczcbMqmDYh0XNv3/FYVN
            WPB5s55FLSWoFtHA5RTvXJpwVNS0Ojof+Sz5E2bEZtjNq38P74Kgzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T01:18:14Z"
    mac: ENC[AES256_GCM,data:bxF62H/V/oVHnmEOQ4B4bwnWZtJo+vc9D7ScB4AH5hvfdVd8Z4Fbdj0GmP+ApUD/5neod2s9nVsy1wwWunZcxhN7BAI6DfNvd1Rs8sNkihuIQ7S9CPZOMgspQLgkWWNEr8JAwdphIWeoAtJusFK2C3YIxxXrSpgt4zhOMZTeI4Q=,iv:4HRPUrzDhzHQIOQ12VpM/XOHBHK4hBXAXgQYUOdCyt8=,tag:CiTKd9JeDzUHRnDGXeCl1A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
