kind: Secret
ansible_user: ENC[AES256_GCM,data:2HJhAQ==,iv:z1N0u6G0oAN9FrbQ9sNFjqfgCaihzW8Mg2vdOK+YXOI=,tag:RylHekRmY9R0S3BBVbzYpg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1QlgxTgsS1JZXg==,iv:KMB8i5pC7I2pfejzU0T2Ozx5XRoM7cAbcS0XAihC/70=,tag:Bna1GfsT5Kk4ZeQsOrJkHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYjAzQURrVzZPUUtDZjIx
            VzQ1SFg0V3ZrbnVqemF5WVh3WDgwdi96TTJvCjZCUURFZ3pmM0pKQkh0Mi9abVBa
            VTJ3eHRKbi9VTFZBRWtCblZMekhkeWsKLS0tIGxsTEhpQ0JmN0lGQ01SdFdFL3o4
            cmlVdlczc2h0T01seVBic0d3Nk02eHMKyQPvOFDfKtKsqR/SuR9IVealq6X7lyVJ
            /ZAKEC2qXrbFOB4tFFHLqFITcxfE28DsIaSiB2POkXrS8Fal3t6CWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T15:03:40Z"
    mac: ENC[AES256_GCM,data:j3g6cw/M6iRDRYQJUpzntTwybSE6bMC2s+//OkaOCuig9OqqDkCOQ3BJiqFGJr5y7GSAAJ+NG15zYH0j5ZYo7aKS9EQGnkxozlzgYolPXJdpU+qbiLJF3PmZS4uSG+TQP9pPQa/6fv7FSrI/2mBFPT/m7UBhilaF0AXpwWcyfak=,iv:Nmznj3Ovk2E+2NkMySakuQ4+tIgqEd+JdYfZjELw5+E=,tag:ml74NEVFqHA3dfYwUSV22g==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
