kind: Secret
ansible_user: ENC[AES256_GCM,data:CAR0zQ==,iv:xXttSkziaINLzeRuqWjKucXod3J4HlR5J9SXlS74Ewk=,tag:g/fhmHYT9d+Op8WiRVrdvw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ukBRbQw6SMz6mQ==,iv:qk0gwndSVkGad8sBYMBglv+MSpNfDoLXy//2SH3N8P8=,tag:8PikrJFb5MBHUV7YhuGwiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZTNwcUpLQ0h3dnFmaXlX
            Ly9ncVVsRlM2Q0YrRUFDQng3dFpZZFNCeVZFCjFWK1VmUXVFWW15bTJ2UDBHS3BQ
            ZGRlVTYyZnBKTHF5M2dkWnF3QU5mV2cKLS0tIDhMckxjZ2kzMUdjc1YrRlVNbjBK
            ZDJGaHZDZDlIbitzVXdOOGh2bTJjb2MKF5Gu8QKCM5UFfzF594dxfkgqVepfsL1v
            TAiRsMeEONLiLs5r8lUrYibLNBhKoVX9TdSuaQI5zcegJNJ+cWuqYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-10T22:32:43Z"
    mac: ENC[AES256_GCM,data:pNzaDjDtLpFOQuQdlt3E/EcqFr1B5WjHj9y7qier+l62HINzA9ZuQf4z1bPycCJieG/2i2ZGa6swih8sBPz4tY/toRT8rga9NGRe7931PQwFkCev83NOaDVdx6GaTey1tQAOANZ130kmEVxr5BcwOAtIGxMPCS/1ALyHPoyiLYg=,iv:8tSiizkg52ytjcUqqP0K8Wl2ul4Lv5hYqWz3oYN8GlI=,tag:RMqxvVRP37V5ZbURauBAUw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
