kind: Secret
ansible_user: ENC[AES256_GCM,data:SDbpTQ==,iv:18qvZc9t6J31MJ11XU8YtR1Rh5DYU/PGi7pujz/WAm0=,tag:d8TsRcwSgNL2D+BXPkuUqw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:CGqX6tyKhw2j4w==,iv:1hydTwptcpD7k9u2M0g8+TJA/+lMk19knRp52wnlOQk=,tag:N/ZOLoQZ+8Jb2JArqLbUGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY1M5b0NDd2d1UUhzbzRH
            THhWWU4rdEtTZklHYkVWVmdDTkx6Z1ZwTzJBCm9mQmVSUnNPaVl3RDdGeDdaRDl5
            Z2lpaFA2T05US1VMUXVZQXVFNzBENFEKLS0tIE5UMjJGZ1k4N1dpUG1VbEdrN284
            WW43YnNSaEZtclZlU2Zsejg1VU5GWEEKIKEwot3dzcg8seMJzenHFljpPe3vYhDH
            MEk77EBm/m59BIWBDl3jVukYVu5472ELXPzYsMoUvECSz7encVLi6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T22:39:08Z"
    mac: ENC[AES256_GCM,data:divgvq1wVjOuK13+Nt4C4ygWIxQyrSgxt4L0rH/XZq/6x/s5mNCB6QSCs0W5hFl0siW4QSh5mi0n1UPuoDmM3MC2a20CCe2wgs/BNg72QPYbOrw9SBgvayaQc1rrlDMm7M9vtoy4CLhtokAWCy+0UMARGGBEEH84yoWKv0yq6/0=,iv:gdcKDqPjNdEYF48EzTm2vXuS/mkIA8N7n7We7WlUlTI=,tag:O+A/sJhVXEdQljuQD7/OBQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
