kind: Secret
ansible_user: ENC[AES256_GCM,data:UkXDMQ==,iv:NVfT8hCAvgJO3WJ9ReOX1qmKt9OaX+S+UuoCsbBWz8g=,tag:qk8tIPu/A76+gC4fRZ8JrQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ewF2t1CgJMOgCg==,iv:HD2vZfiqjux25hLjGTw7cQjapcnO7hJ/KDW4bOr9gM4=,tag:QlzWCOAvtIkIqHEZnPZ6oA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM0h4cm0vQUF1N1FRZ3dR
            Z1RYSEZvSXV0OWdHblhhZEhsdVZUbEpZc2pFCmg1SlQ3UXZIOVFPd0Zrd244L2pU
            MSt3Q2ZjdUxzZ2pRUGYwUWY4NUNXUDAKLS0tIDE1Z1dXbVZvZHhJQ1k1QUV0eGt4
            TmhmNDJ4bFh3MFZKdWJEQUxvaE1oSWsKiw5rp4VPfM0GRbDa0/JLp39QPjmeyPak
            T6TKIFrL8oGlj6IAzj36ddr2tdlOX7yLbF7zY4wo4VlgpkHtRthaPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-13T00:42:53Z"
    mac: ENC[AES256_GCM,data:eGwwJtGKvcFl0BZpggPKD1PdYh5Bv6QeyQvYV8wjhFwHIYnDGxOVgdYz0upeC141bMWaENNScVuHAphBEkQN2QFIG3oKUOnVx4URANfPszOWhieYKl1W9yvpKSa7BdOiEZif65RKf3smLCDtUwp6qghefMfKS27m7n/DdHMOE7c=,iv:xvimWxqOMSVWKEi2rbYUXOymhiUkFTlZ5X3pxtat0Fk=,tag:9r84g88cNQdVWXrh4uiqDw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
