kind: Secret
ansible_user: ENC[AES256_GCM,data:4WEF/g==,iv:KuJm+9C0kqzQdUtYp/l0Q/NC4xPVtmWtuXFnNJv6a/Q=,tag:/LOgO1JvoEAQDdoQ/c5zhw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cO8ntyF1PM8qmw==,iv:6O7oKYmqovDTinvliJza6BnMNY0MoS9KDU7liWdvUcU=,tag:gdYFY23IebZUz7wY+6NZhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUExvbzIyVVRDaFNWWXVw
            SzExdXJpcVV5RGJnY0JoM201b3pObS83bGdrCmszUUtlLzYxU3NUamZkQ0tTaHYx
            ZENGaWtPdVlkaUdNK0Uxc2IzRE4rWUUKLS0tIHlqWEpicFcyZlhFRXpBSDk0RXhm
            cW04OWRsd0pyZDBDSys2czZhVnB4VWcKl/o1M9nI9/pV+D30t16BuVj3urhBl4IC
            W5hSUk3xA6ITYx0zIRwxNwfEgmKbeYx/BfwL9al5lrhlt2I1Ig82uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T17:28:30Z"
    mac: ENC[AES256_GCM,data:QQKRSe0soBDe8NNGVUlnsCJp7+uMW6tVCKQKgWrYRNxQZuoaB7eyI3654ub+u5lLZHKP+jCRgAK/PJBQGAJkYpGupQcQ1U6IRAn2pP2CDfxi9GMi9yKJjhr+rOpn/5s5gC1Nd9bP31NJrnLSFm/wly+pIbEJAazK9Si3LYkryrM=,iv:KeR+gz4vmAcFysoxAuMVG0T2ulZsdioUJjnDoktI3uU=,tag:QdL+QjpB6c6R9MUjbd8kgQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
