kind: Secret
ansible_user: ENC[AES256_GCM,data:/0f0fQ==,iv:BCkICtk0BPEliGXzDvsZuFKI22GQNSsgHozA4KL30Gw=,tag:Luu9rvA2mMiSYh2kFh0MMQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:55kNBxXeyuIRTw==,iv:hmZBH5K6E6dP7MDtwAJI7ly9fq3R2rn20n8Bij05vCE=,tag:aCiGr0za/3jCJwEL/iFtng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMVZQM2tCVzc2dkdvbVpa
            V2ZWTkxYSk9mdTBWM05kdVRaQnJ5SlRFZlFBCnlDTllUVmhnWGs3OVpld0xTLzI2
            TmhrajJDVDdjMjhVK1lFTE1Fa1ZramcKLS0tIDVEaTVja1c4TnhXek02djNlNDha
            ZG5wWFM5OURiaWZCem13Ujh1U2tYQWcKdOOHYyTUncm25rWYCK1cY5KBQy1d8EXi
            Br23YTHu3u+c54KLkqpI3n8TmDkaENxRPAiXSbUo7l8TxCV+1iNzFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-25T14:51:02Z"
    mac: ENC[AES256_GCM,data:b7yx6UkTBdBAm+/ff2OlILyW0qn57XJAa8hH8f/kIFcduWrnX/hPO0tfNVlmJSs3blHPySXNkmNoBbzwYrYakm/bykI9jOEar65B7WO1nCTuQi7GFIg0Q9vx8y/DbqnIhx3/tvPwjVbNxfFoJd3Uq1aiaX6jWq2Rl58e+Flz2qY=,iv:23uwjVZ+ybfejLhFzX/SOjAsPGFGg3c0GhWZ/GANnt0=,tag:dAPFfjnjJyuDen4SVEguAw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
