---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-browser-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-truenas-iscsi-retain # use csi-truenas-iscsi-retain if redeploy
