---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-v1
  namespace: media
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-truenas-iscsi-retain # use csi-truenas-iscsi-retain if redeploy
  resources:
    requests:
      storage: 1Gi
