---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 5.5.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.7.0@sha256:ce4871ccdfb98e8dcb5330125a06954ca3b40d9cff3235fb39ac2ba33feff0ff
    updateStrategy: Recreate
    routed_namespaces:
      - downloads

    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.5.0

      gatewayDefault: false
      gatewayLabel: setGateway
      gatewayAnnotation: setGateway
