---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring
  - backups
  - books
  - media
  - downloads
  - default
  - flux-system
  - kube-system
  - networking
  # - system-upgrade
