---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-ruler-local-path-v1
  namespace: monitoring
spec:
  bucketName: ruler-v1
  storageClassName: local-path
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: mimir-tsdb-local-path-v1
  namespace: monitoring
spec:
  bucketName: tsdb-v1
  storageClassName: local-path
