---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - overseerr
  - radarr
  - radarr-uhd
  # - sonarr
  # - sonarr-uhd
  - bazarr
  - plex
  - jellyfin
