apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        meta.helm.sh/release-name: nfs-democratic-csi
        meta.helm.sh/release-namespace: democratic-csi
    name: secret-democratic-csi-driver-config-nfs
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:RB7Ee/TEHHNGY5WYmCe5NM5N0FL4Bqqjgb64DwCvdmI1T7OkWlb0jDLTjURvpw8WTVhxZqABAgI9peYFovmkXr91v1sHNHUY/+baR2zRaLy+GZo5dB0HgU1bpjguHHaa4h2sl6/jCA+kzTKMgpmRJ6FLL7mgXhebKWLsuQttW5JIAe6dDI/pP0HKS1PSQ2LSjj2af+xEVI3UgCSjXbVuqkEREEu7j+08oaAOLEnV7Zvxcso+9vXUIYqDr2JEnEs5FBOSvsg4jw06speHSoBPv4PQRWUeRaaUowhhbOhgMTwZu+idIcQHQZlfI/FVPVrjh92LMzwwqU9qPDD2bp2nI1JoJklyJQnbjqlmlH42TqJ+SPPXPAnp+KZDI7HbtJnYT+wu8uWaaQOYMBChXp3Jr83bIsfzEIxZJQixuxrwuVeuSdhfSv6jWBJwfVUEFYw5iNl29HVUQ6thwTb5qhlQOArW8qKNlhs0Rz1mzNYBBgO0ILqIBXAEudKHChlwpK9C4Wy9p+Y6gtqoYX5Z72iiR4iv97iros+3qOYcS6LrC+YlLJZwbHOAPhM+NB945i+VCifJLMoFOl4f5zko59yKbBPdXEeF9udONfpeHBQ+e1fp4V8b0tcuqZdZpxIeMeJ5PPPSqxtAN24rZcX1hmsKK20qxCHfQL7PmXETciB1HicoN9nROlf5ecUDBf6SUU02UOlI6f5KSGjIi+4yg6BmDZt09denwJJUb4z1ItROyVmxRYB2GhMcjrgwQtrfBAvRmn+H7EuEXF6qpX5BmUcDhZRAZmBtCUylZFhqRSSlBHTAcctROiXZ5u4hxglDO7ywaaRfJJAbexBwqPxwqivavloANY942jObONYNSHNoroO/d9wL32G5ZNOvbuC8PmOek2M+nilrGDbbfHXA16X9LrKS/VcjisUn5Jr5PF7FLl4rtyB4ugN6YStHCwDYVZMgZ5lY5tOHo3PTKKRpYWBjh0lHoTf2DCjkuiO+yxfVD2Laiq0QZlK2cROSOTfTF4y+M4BDP/o1vmtLa3gTmsO4nm4cpoofap/B55iZ/qhhjByXS4QWtheGhxm6J9qS2Fb6VIV1MyfDaum0GPOzJ0oVpVA8fP1TNC7becmBqjdjDje3w9ZWdFHUHurmEMC57CsRr5PFpb0lNIL54KjWn/R8ZPrJj22KcFEerjWni6RsAXioNvPwgtiCMPWbmf70Mq0GXXYioYp1vQv/NRHMRX0B5UQCepUYUSFM4hN+hGQhPuJ8spwL5eS6X0RVe4/I041zbvzXm1cwp6bkufE6iAJX8ove/lVeI983orMaSvVONQ/VQd/tNi0dfClZX3z3f/IU8ZeDmV1lOcLxxYAAOneoBy9Donf8ecb18pbkf0gbMj1nHsREaO+lseaVDwPGJYFoOb+wpMKd9cu8Z3UKzfw6zL5enRdMaYa3OQ39BQ/frAv6Su9iu407UQH1DR6gnnrBs7KIPJp/cewrDE9cw22SUHJF3w224YyoxChjNvW2221djTKC+++VbyoAxZKjqbwuFZW/fPVPgg1fgs4D0lfCHh15mVm/13g5s4E7se4/BgzBzPN8keITtgq4GxoMp6nhKinrPwg8AfJXdRxi+hB6bn9uVpI0puX9Ct+XwHvxMXvpd+cfRVJQX8xwe3LALnr5XLVxB5Ia1IprabrustkTltYYpVQ8vXEIKdkhwIzd+N2MYrum6I6hJDgMevblrGYjqYXXCxMSl/VXFiVNyrbS+ZPq86Y7wkeYepkNuvf/vsTp9DR3zDEvsqwJAUF6mUQXWpE1RFQ0qtp7YJMsHOzaBRJS5HwpsfA+tVlCkh7ZgYM0Q61QvVqh7sreT4dGEnTIcRoiQ7oS2VmvCkZThoefivKzkmDSxbHUjNwIxmRnJg/h1Z+FmH+ipyJcCjeVuYMM/qSXSesu2ux1Xr1u22ndIvQ015xOWZIvve34YhtbUJ+lZdTOJhlba3/uurR5eufsFiG2NfjFhcRJbCF6L2h2J46jIsSu4YGWi2THmfHEUkm0kabofg3MMdEvEhtMS52xe0RhzUSaL1CcDPR6zsVfhwznrYHhDkqdf0kM9J6dielHelXMjN/gALVlHrLBoUrl2KsvbQiDdpeKJEntiVIP7RSfQmMggIcBDQ2ojjM8DS7MdBAFOHThptwbCq4XpjXVKVluot4IYwxVsOwnXlOOpQ8GwFVfyr8UPNZ88BfKbx4H9SG/FVGdPi25pnJGh1Qxze2sAfU9kG9FVp+BJ7cGzYF1ywV4RUF/MnvQ/euKu3d1zvaCwBVtQxmMAygBzrtCOMWDnSyJ9YJOTgIHckdGE1xyzHyrXyGzAbGZsML5GifuRGFLOSE7Dn1b8eQBh4rAX/oR,iv:4M3c2O+WjR0BvAWapD7IxHajyXisFA4C5l7xzDmBJ4M=,tag:z62RO8RidXtprxRwwSlzqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVThCVlpadTVxektCOTAv
            OUJsMXNuYWFPVTR2UHUxNzVJRE85bTJYbG44CmhUNXljN0MrZFU5WFlnZTFZYjRx
            WTYxakU2byt5bFNMR3lYTVE1eXU5cUUKLS0tIDBaQ3c5UG5tTVFBb01QSm82TVpn
            bStUNGNSZ2h4bmp4Vkg4TGRSendkeWMK9lR+lNqlcugcAhRh8pamWepsDEJrLVuw
            Uvj5BparapY4WOHhZ7OFkG+XvuKEwy+xTpIEbVhEsGZpht6yzevIHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-06T00:31:37Z"
    mac: ENC[AES256_GCM,data:FSZTYeRDKK/4TJm1TZQdTnnMXxmEKll6o8qIQPBzyicFtaUCKEtoEH/ispykXurccd1/5ucPfWvooFKZNOsq/6t9zYFV7JnJ1BoVKNZow/xA2hmXtSn5kjcnuja/GylPMTj8tP+fGsmv9CBon7eSJeqUdCAI+vAgPVnf0Ybl0E0=,iv:HAzmhSLeqwtmvv+v7lk+WmlBF+xCeoMZ9NY5YpZC4zs=,tag:QA2N8cswCmEhm/ZZ73h5hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
