apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: downloads-gateway-vpnconfig
    namespace: vpn
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:l4tiRbYhJA==,iv:cLUH0vazip9u9UlNMVtJJUYSaVl0WwTfNP3WBacIueE=,tag:ty7qhwukE0xmgrf1WiXPrw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:CXMaAuhI4Wey9Abw95lx0j1c6QXVuPWOTlVYd1KF/Eu4C+ETvMvyunMUDDs=,iv:rYjd12JcSms9B7PLVLM8S7lNJjP4tddK+Q2/TOMXPNI=,tag:ejde7Qy/ciMV4bpkNYkMcA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:t8yWzqpiSfnkFw17wcGJqg==,iv:GmfDBxFKgb0ZHNP2iGiPcrZglK5Y3sofBy7CryWsaYs=,tag:9KUzrTbBQE1n6/4jvk4gEg==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:5soP,iv:V3LJV6Vcag/mJfn6mjTnrm3mODuSI3iPgtalMONCgzA=,tag:PlkSMXK1kaIgtaUpt9PsiA==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:GEmf,iv:mKTdDDV2QPFFir5FGoSCtELzeZv+6jlvYJihrh9FT4I=,tag:BHNnny5zz+sGTmvLTeXkEA==,type:str]
    SERVER_HOSTNAMES: ENC[AES256_GCM,data:syWnXWPwIakry5OmrGkN,iv:7UU8A9tVQMOHExTRaw9Tv2HkXBGIbgA7umFeIEiFdpU=,tag:u7eTGjCrGT4xVGXLq2dlNQ==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:szTi9lI=,iv:wGd/iSnG8aBC3YOO6SHYc4woiTR1/BWMn8/dOFpBb38=,tag:bqSpxTOl6f1YNvhF62/fig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1plaqfnumz9dcvqvtns22kmv7kywv7afgatg7v3yeqfmd8f8kd92ssmvkge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVVBabTFFVHlCdmVJZG5k
            N2ppeGlySkJFT0hKUFExM2lya0ZjTGpseGcwCjRlRVhUVEhSYVVIQU44OVdKSE9s
            VTlnTTFQZDh0bXBzTDRDdlYyaFYzMWcKLS0tIDF1aVZoN0JyM1VHanlibW1DZEdt
            RnJybUZCY2R4L0xUZFErUFZxb3d4UFEK4Fu1Yqa4wFcl1l4QJn6xoWbBID4I+sQf
            1WdwkfwOFaZNzPZkIWMCKo+++voquUcpZzXYn/dHmk7D1QHyEGvuwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-15T16:17:06Z"
    mac: ENC[AES256_GCM,data:YREAOlqk+7E74+PadTstmE6jk/PaUOkDrCe8UkLbfvB6y2djaPhUnSnBR/NxXdQdcwKxQZ53xJoVH4W0brM9Wt7jVPsay+ouwswepzTCzMLkwOnZCguVad7aYjahARthGEadUJ1nNhbp0UO2gE/pyPod0NwC/7SkLPKLcNQzIBU=,iv:fkjRvebjwvHG5tMb+vzRXnjKpdY7DwnEzSpjw11Dg14=,tag:9y8dQryu41lUM8947tKJkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
